### ISSUE TITLE
Crash when inferring a tree on a simple alignment

### ISSUE THREAD

**Issue by arvestad** [iqtree/iqtree2#103]
Hi,
Thanks for a nice software! Unfortunately iqtree2 crashes for me in some circumstances. I run this on an iMac with a quad core Intel Core i5 running Monterey. 

I have attached the Fasta-formatted alignment and log from running version 2.1.2 of iqtree, installed using "conda install iqtree2". The command is essentially `iqtree2 -safe -quiet -s a00009.fa -m TEST -pre a00009_modelfinder`. The alignment looks simple and can be used by PHYML without a problem. 

The crash seems to be after finding a starting tree (rapidnj) and when it is trying to fix negative branches. 

[a00009_modelfinder.log](https://github.com/iqtree/iqtree2/files/9565131/a00009_modelfinder.log)
[a00009.fa.txt](https://github.com/iqtree/iqtree2/files/9565144/a00009.fa.txt)

**Comment by arvestad** [comment]
Update: v 2.0.3 doesn't crash on the same data.

**Comment by bqminh** [comment]
I just tested v2.3.4 and it works on your alignment. So this bug was fixed sometime ago, which we forgot to comment here.
