### ISSUE TITLE
Version 2.2.0.7.mix binary

### ISSUE THREAD

**Issue by francicco** [iqtree/iqtree2#106]
Hi,

I wanted to try the new MAST protocol. I've seen from the preprint that the Version 2.2.0.7.mix supports it. Unfortunately the binary do not work:

```
./iqtree2: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./iqtree2)
./iqtree2: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by ./iqtree2)
./iqtree2: /sw/lang/gcc-7.5.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./iqtree2)
```

The Version 2.2.2 does work, that version has the implementation?
Thanks a lot
Francesco

**Comment by thomaskf** [comment]
Hi @francicco ,
Sorry for the late reply. The MAST model is now available in version 2.3.0 or later. Thanks.
