### ISSUE TITLE
Alisim problem with the Gamma distribution when using mixture models

### ISSUE THREAD

**Issue by lucanest** [iqtree/iqtree2#109]
When trying to simulate an alignment with a mixture model and a continuous Gamma distribution on rate heterogeneity across sites, we encountered a problem.
We could not specify the continuous distribution: by default it had 4 categories, and it used a default alpha value of 1.0. Our command:
iqtree2 --alisim alignment_aa.fasta -m LG+C60+GC{0.5} -t tree.nwk
was apparently interpreted as:
LG+POISSON+G+FMIX{C60pi1:1:0.0169698865,C60pi2:1:0.0211683374,C60pi3:1:0.0276589079,C60pi4:1:0.0065675964,C60pi5:1:0.0141221416,C60pi6:1:0.0068774834,C60pi7:1:0.0146909701,C60pi8:1:0.0067225777,C60pi9:1:0.0018396660,C60pi10:1:0.0102547197,C60pi11:1:0.0230896163,C60pi12:1:0.0057941033,C60pi13:1:0.0125394534,C60pi14:1:0.0204526478,C60pi15:1:0.0070629602,C60pi16:1:0.0117982741,C60pi17:1:0.0068334668,C60pi18:1:0.0433775839,C60pi19:1:0.0318278731,C60pi20:1:0.0222546108,C60pi21:1:0.0102264969,C60pi22:1:0.0150545891,C60pi23:1:0.0134159878,C60pi24:1:0.0148552065,C60pi25:1:0.0239111516,C60pi26:1:0.0128776278,C60pi27:1:0.0222318842,C60pi28:1:0.0247444742,C60pi29:1:0.0214274810,C60pi30:1:0.0115001882,C60pi31:1:0.0076017389,C60pi32:1:0.0130258568,C60pi33:1:0.0093701965,C60pi34:1:0.0467194264,C60pi35:1:0.0441940314,C60pi36:1:0.0322263154,C60pi37:1:0.0402999891,C60pi38:1:0.0150234227,C60pi39:1:0.0104589903,C60pi40:1:0.0214742395,C60pi41:1:0.0154957836,C60pi42:1:0.0101789953,C60pi43:1:0.0227980379,C60pi44:1:0.0123204539,C60pi45:1:0.0066777583,C60pi46:1:0.0004150083,C60pi47:1:0.0344385130,C60pi48:1:0.0113663379,C60pi49:1:0.0127143049,C60pi50:1:0.0124323741,C60pi51:1:0.0262124415,C60pi52:1:0.0064994957,C60pi53:1:0.0103203293,C60pi54:1:0.0142463512,C60pi55:1:0.0215600067,C60pi56:1:0.0199150700,C60pi57:1:0.0038964200,C60pi58:1:0.0113448855,C60pi59:1:0.0128595846,C60pi60:1:0.0117656776}+G{0.5} (notice the extra +G at the beginning of the model definition.)

We were able to use the full model specification to change the alpha parameter to any value, by removing the extra +G, but we never managed to get the continuous gamma distribution to work.

**Comment by lucanest** [comment]
Dear Nhan,

Thank you for the rapid reply,  I have tried the command you pasted but it still doesn't work (Indeed I had already tried that), is it working on your machine? 
I still get
'Model of rate heterogeneity: Gamma with 4 categories'

Thank you,
Luca

**Comment by trongnhanuit** [comment]
Hi Luca,
I got it now. I checked and can confirm that it is a bug only on outputting the name of Gamma model. In fact, AliSim uses the continuous Gamma model but shows the wrong name 'Model of rate heterogeneity: Gamma with 4 categories'. I'll fix it. That bug fix will be included in the next release. I can confirm that this bug won't affect the simulated data so you can use the current version and don't need to wait for the new release. Thank you for reporting the issue.

Please feel free to let me know if you have any questions. Many thanks.

Cheers,
Nhan

**Comment by lucanest** [comment]
Dear Nhan,

Ok, got it, thanks for looking into this!

Cheers,
Luca

**Comment by trongnhanuit** [comment]
Hi Luca,
I fixed this bug which will be included in the next release.
Once again, thank you for reporting the issue.

Cheers,
Nhan
