### ISSUE TITLE
Potential consequence of reduce -ninit

### ISSUE THREAD

**Issue by hrluo93** [iqtree/iqtree2#112]
Hi, 

Iqtree is a wonderful and excellent program.

I have a problem when I used the whole genome multiple alignment seqs to construct ML tree with 100 bootstraps by iqtree. Because more than 500 Million sites were used, the running time of  INITIALIZING CANDIDATE TREE SET was quite long. 
So I set -ninit 27,  and iqtree reported Generating 25 parsimony trees and Do NNI search on 20 best initial trees in this process. Does this reduced init tree searching influence the topology of the final bootstrap consensus tree? Does this setting reasonable? 

Thanks a lot!

Beat wishes!
Ran

**Comment by bqminh** [comment]
I don't see any problem with this. High `-ninit` is needed for short/medium-length alignments with potentially low phylogenetic signal, and high -ninit helps to navigate tree space better. But you say to have 500M sites, which is obviously not the case here.
