### ISSUE TITLE
using -fconst

### ISSUE THREAD

**Issue by alanxelena** [iqtree/iqtree2#113]
Dear all,

  I'm running IQTree on SNP data generated after running snp-sites. My idea was to use -fconst to input the values of constant sites as suggested by Torsten Seeman (https://bitsandbugs.org/2019/11/06/two-easy-ways-to-run-iq-tree-with-the-correct-number-of-constant-sites/) but I don't really know if I should also input a model (using for example -m TEST). My doubt is whether the selected test parameters will override the fconst values that I supply.

Thanks!

**Comment by bqminh** [comment]
There is no problem, `-m TEST` is independent of `-fconst`. After reading the input alignment, IQ-TREE will sort of add 4 constant site patterns (for DNA) with corresponding frequency of appearance from -fconst, and then perform everything else it normally does with other options.
