### ISSUE TITLE
Providing internal node names when simulating with option `--write-all`

### ISSUE THREAD

**Issue by Boussau** [iqtree/iqtree2#116]
Hi, 
thanks for your very nice piece of software!
I am trying to use alisim to simulate both a tree and an alignment, while keeping internal sequences. It works well but the names of the internal sequences in the alignment are a bit mysterious because they don't appear in the tree.
Here is a test command: `iqtree2 --alisim data/alignment_123 -m JC -t RANDOM{bd{0.1/0.05}/4} -seed 123 --write-all --length 10`
which produces the following phylip alignment:
```
4 10
T3        TCTTGCCAGA
T4        TGTTCCCAGA
5         TGTTGCCAGA
T1        TCCTGGCAGA
T2        GCATGGCAGA
40        TCCTGGCAGA
```
but the tree does not have the internal node names:
```
((T3:0.0291379968,T4:0.0166094038):0.3631162715,T1:0.0127361633,T2:0.2840921818);
```
Could we get the tree annotated with internal node names instead? Thanks!

**Comment by trongnhanuit** [comment]
Hi Bastien,

Thank you for using AliSim. It's definitely a good idea to output the
internal node names. I'll plan to implement that feature and will let you
know once it's done (note that it may take a few weeks due to other tasks
in the queue).
Thank you and Happy New Year!

Cheers,
Nhan

**Comment by Boussau** [comment]
Thanks Nhan! I think I noticed another issue that you can see in my original post, while you're at it: the phylip header of the alignment file says `4 10`, but since there are 6 sequences, I think it should be `6 10`. Good luck and thanks again!

**Comment by trongnhanuit** [comment]
Hi Bastien,
Since the latest version 2.2.2.7
<https://github.com/iqtree/iqtree2/releases/tag/v2.2.2.7>, AliSim will also
export a tree (*.full.treefile) with internal node names when users output
internal sequences. Hope it is helpful for your research, and thank you for
your suggestion!

Please feel free to contact us if you have any questions.
Cheers,
Nhan
