### ISSUE TITLE
-sup mapping of non-bootstrap values?

### ISSUE THREAD

**Issue by JGLAHE** [iqtree/iqtree2#117]
Hi,

I've may have missed this in the documentation, but is it currently possible to map non-bootstrap support values onto a target tree?
I was hoping to get around the issue of not being able to combine --gcf & --scfl.

Example command in v2.1.2:

`./bin/iqtree2.exe -sup concord_gCF.tree -t concord_sCFL.tree -v`

Relevant output:

`Reading tree concord_gCF.tree ...
Tree contains 121 taxa and 239 branches
unrooted tree detected
Reading tree(s) file concord_sCFL.tree ...
1 tree(s) loaded (0 rooted and 1 unrooted)
Using hash_map
Converting collection of tree(s) into split system...
Rescaling split weights by 100.000
239 splits found
Creating bootstrap support values...
Tree with assigned support written to concord_sCFL.tree.suptree`

Cheers

**Comment by bqminh** [comment]
Hi there, this is not the right way. The correct one is:

iqtree2 -t concord_sCFL.tree --gcf TREES_FILE

where TREES_FILE is the file with trees you normally used to compute gCF.

Cheers
Minh
________________________________
From: JGLAHE ***@***.***>
Sent: Thursday, 5 January 2023 11:27 PM
To: iqtree/iqtree2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [iqtree/iqtree2] -sup mapping of non-bootstrap values? (Issue #117)


Hi,

I've may have missed this in the documentation, but is it currently possible to map non-bootrap support values onto a target tree?
I was hoping to get around the issue of not being able to combine --gcf & --scfl.

Example command in v2.1.2:

./bin/iqtree2.exe -sup concord_gCF.tree -t concord_sCFL.tree -v

Relevant output:

Reading tree concord_gCF.tree ... Tree contains 121 taxa and 239 branches unrooted tree detected Reading tree(s) file concord_sCFL.tree ... 1 tree(s) loaded (0 rooted and 1 unrooted) Using hash_map Converting collection of tree(s) into split system... Rescaling split weights by 100.000 239 splits found Creating bootstrap support values... Tree with assigned support written to concord_sCFL.tree.suptree

Cheers

**Comment by JGLAHE** [comment]
Cheers Minh - thank you very much for that!
