### ISSUE TITLE
Segmentation fault with mixed protein+DNA partition

### ISSUE THREAD

**Issue by morpholino** [iqtree/iqtree2#12]
Hello,

sorry to post here instead of Google groups but I cannot seem to join that. I am experiencing an apparently unreported segmentation fault on a rather small dataset of 8 proteins and 1 rDNA matrix (altogether ~4300 characters). After loading the input, IQ-TREE consumes 90GB RAM and crashes. This does not happen with version 1.6, or with protein and DNA partitions analyzed separately. Would you kindly advise me on this?
I am attaching the log file. [partition.nex.log](https://github.com/iqtree/iqtree2/files/5541394/partition.nex.log)

Many thanks, kind regards

Zoltan

**Comment by bqminh** [comment]
Sorry for the delay. Did you use version 2.1.2?

Can you check if it works with version 2.1.0: https://github.com/iqtree/iqtree2/releases/tag/v2.1.0 <https://github.com/iqtree/iqtree2/releases/tag/v2.1.0>

Minh

**Comment by morpholino** [comment]
Dear Minh,

I confirm that we have tried precompiled versions 2.0.8, 2.1.0 and 2.1.2 on
servers with ubuntu 16.04.6 and 18.04.3LTS with the same result (we also
tried locally on a computer with ubuntu 20.04LTS but in this case we
quickly ran out of memory). We did not try compiling any of the earlier
versions. Sorry we could not narrow down the problem more.

Best

Zoltan
---
Zoltán Füssy, Ph.D.
Evolutionary protistology group
Faculty of Science of the Charles University, BIOCEV
Průmyslová 595
252 50 Vestec, Prague
Czech Republic

zoltan.fussy@gmail.com

**Comment by bqminh** [comment]
I don't see any Segmentation fault from the log file, thus it's hard to say without running IQ-TREE myself on your dataset. Moreover, there has been a lot of versions since then and thus I will close this issue now. However, please feel free to reopen it if you see that the latest version of IQ-TREE still crashes, and in that case pls send us the input data.
