### ISSUE TITLE
Testing constrained tree

### ISSUE THREAD

**Issue by DarGuerrero** [iqtree/iqtree2#120]
I have IQtree multicore version 1.6.12 for Mac OS

I'm treating to do a concatenated file with my constrained trees using the 'cat' command, just like the manual of IQtree saids!
But the program can't follow the instruction and shows the following message:

bin/iqtree cat example.unconstr.treefile example.constr1.treefile example.constr2.treefile example.constr3.treefile > all.trees
ERROR: File not found cat

Please, help!

**Comment by thomaskf** [comment]
Hi,

"cat" is a bash command. Please try again without "bin/iqtree" in front as follows:

cat example.unconstr.treefile example.constr1.treefile example.constr2.treefile example.constr3.treefile > all.trees

**Comment by DarGuerrero** [comment]
Thanks so much, Thomas! ;)
