### ISSUE TITLE
Rootstrap_Inferring_rooted_trees_without_outgroup

### ISSUE THREAD

**Issue by KatherinOtalora** [iqtree/iqtree2#121]
Hello everyone. 

I share my issue. 

I have been running the Inferring rooted trees without outgroup:

> iqtree2 -s file.phy -spp file.nex -b 1000 -safe --prefix rev_dna

but I don't get any .nex file with the best partitioning scheme.

On the other hand when I run this line: 

> iqtree2 -s file.phy -spp file.nex --m 12.12 -b 1000 --prefix nonrev_dna

Using the same partition file (file.nex), I don't get the .nex with the Rootstrap.nex either.

What do you think is the problem? 

I only have 8 outputs with .bionj .boottrees .boottrees .ckp.gz .contree .iqtree .log .mldist .treefile

**I have noticed that the manual that is online is not updated because I had to change -B to -b, -p to -spp, --model-joint to -m.** 

I don't know if there is a new manual available with these changes and also maybe the explanation why I don't get any .nex file in the analysis runs. 

Thank you very much for the help.

**Comment by bqminh** [comment]
Hi Katherin,

Which version of IQ-TREE did you use? Can you send us a log file.

Minh

---
Minh Bui, PhD
Senior Lecturer
School of Computing, Australian National University
Canberra, ACT 2600, Australia
Hanna Neumann Building, Room 4.16
145 Science Rd
https://bqminh.github.io

On 10 Feb 2023, at 12:16 am, Katherin_Otalora ***@***.***> wrote:



Hello everyone.

I share my issue.

I have been running the Inferring rooted trees without outgroup:

iqtree2 -s file.phy -spp file.nex -b 1000 -safe --prefix rev_dna

but I don't get any .nex file with the best partitioning scheme.

On the other hand when I run this line:

iqtree2 -s file.phy -spp file.nex --m 12.12 -b 1000 --prefix nonrev_dna

Using the same partition file (file.nex), I don't get the .nex with the Rootstrap.nex either.

What do you think is the problem?

I only have 8 outputs with .bionj .boottrees .boottrees .ckp.gz .contree .iqtree .log .mldist .treefile

I have noticed that the manual that is online is not updated because I had to change -B to -b, -p to -spp, --model-joint to -m.

I don't know if there is a new manual available with these changes and also maybe the explanation why I don't get any .nex file in the analysis runs.

Thank you very much for the help.

**Comment by KatherinOtalora** [comment]
Hi

Thanks for your reply 

IQ-TREE multicore version 1.6.12 for Mac OS X 64-bit built Aug 15 2019
Developed by Bui Quang Minh, Nguyen Lam Tung, Olga Chernomor,
Heiko Schmidt, Dominik Schrempf, Michael Woodhams.

Kind regards,

**Comment by KatherinOtalora** [comment]
Hello

I had the same error about .variants and I solved it by downloading the latest version. When running the following line:

/Users/katherin_otalora/Documents/iqtree-2.2.0.8-MacOSX/bin/iqtree2 -s nonrev_allsamples_new_version.varsites.fasta -m 12.12 -m GTR+ASC -B 1000 -T AUTO -st DNA --prefix nonrev_allsamples_new_version_1.
I get the following outputs:

Consensus tree written to nonrev_allsamples_new_version_1.contree.
Reading the input tree file nonrev_allsamples_new_version_1.contree
Log-likelihood of the consensus tree: -5501.780

Analysis results written in:
IQ-TREE report: nonrev_allsamples_new_version_1.iqtree
Maximum likelihood tree: nonrev_allsamples_new_version_1.treefile
Likelihood distances: nonrev_allsamples_new_version_1.mldist

Results of ultrafast bootstrap approximation written in:
Split support values: nonrev_allsamples_new_version_1.splits.nex
Consensus tree: nonrev_allsamples_new_version_1.contree
Screen log file: nonrev_allsamples_new_version_1.log

But I am looking for the name.rootstrap.nex, I see a splits.nex here, is this the same as the .rootstrap in the new version?

Thank you,

**Comment by KatherinOtalora** [comment]
Hello

I had the same error about .variants and I solved it by downloading the latest version. When running the following line:

> /Users/katherin_otalora/Documents/iqtree-2.2.0.8-MacOSX/bin/iqtree2 -s nonrev_allsamples_new_version.varsites.fasta -m 12.12 -m GTR+ASC -B 1000 -T AUTO -st DNA --prefix nonrev_allsamples_new_version_1.

I get the following outputs:

Consensus tree written to nonrev_allsamples_new_version_1.contree.
Reading the input tree file nonrev_allsamples_new_version_1.contree
Log-likelihood of the consensus tree: -5501.780

Analysis results written in:
IQ-TREE report: nonrev_allsamples_new_version_1.iqtree
Maximum likelihood tree: nonrev_allsamples_new_version_1.treefile
Likelihood distances: nonrev_allsamples_new_version_1.mldist

Results of ultrafast bootstrap approximation written in:
Split support values: nonrev_allsamples_new_version_1.splits.nex
Consensus tree: nonrev_allsamples_new_version_1.contree
Screen log file: nonrev_allsamples_new_version_1.log

But I am looking for the **name.rootstrap.nex**, I see a splits.nex here, is this the same as the .rootstrap in the new version?

Thank you,

**Comment by KatherinOtalora** [comment]
Hello

 I solved it by downloading the latest version. When running the following line:

> /Users/katherin_otalora/Documents/iqtree-2.2.0.8-MacOSX/bin/iqtree2 -s nonrev_allsamples_new_version.varsites.fasta -m 12.12 -m GTR+ASC -B 1000 -T AUTO -st DNA --prefix nonrev_allsamples_new_version_1.

I get the following outputs:

Consensus tree written to nonrev_allsamples_new_version_1.contree.
Reading the input tree file nonrev_allsamples_new_version_1.contree
Log-likelihood of the consensus tree: -5501.780

Analysis results written in:
IQ-TREE report: nonrev_allsamples_new_version_1.iqtree
Maximum likelihood tree: nonrev_allsamples_new_version_1.treefile
Likelihood distances: nonrev_allsamples_new_version_1.mldist

Results of ultrafast bootstrap approximation written in:
Split support values: nonrev_allsamples_new_version_1.splits.nex
Consensus tree: nonrev_allsamples_new_version_1.contree
Screen log file: nonrev_allsamples_new_version_1.log

But I am looking for the **name.rootstrap.nex**, I see a **splits.nex** here, is this the same as the .rootstrap in the new version?

Thank you,

**Comment by KatherinOtalora** [comment]
Where can I access : iq-tree version 2.1.3? 

Thank you very much for your help

**Comment by KatherinOtalora** [comment]
Hello,

I have a new problem.

I am trying to run the following line, because I am looking for the .rootstrap : 

> ./iqtree2 -s rev_allsamples.varsites.phy -p partition_prueba2_rev_allsamples.best_scheme.nex --model-joint 12.12 -B 1000 -T AUTO -pre partition_prueba2_NOrev_allsamples

And I get an error:

ERROR: phylotree.cpp:2751: virtual double PhyloTree::optimizeAllBranches(int, double, int): assertion `fabs(new_tree_lh-tree_lh) < max_delta_lh' failed.

ERROR: STACK TRACE FOR DEBUGGING:
ERROR: 2 _sigtramp()
ERROR: 5 PhyloTree::optimizeAllBranches(int, double, int)
ERROR: 6 PhyloTree::testNumThreads()
ERROR: 7 PhyloTree::ensureNumberOfThreadsIsSet(Params*)
ERROR: 8 runTreeReconstruction(Params&, IQTree*&)
ERROR: 9 runPhyloAnalysis(Params&, Checkpoint*, IQTree*&, Alignment*&)
ERROR: 10 runPhyloAnalysis(Params&, Checkpoint*&)
ERROR 
ERROR: *** IQ-TREE CRASHES WITH ABORTED SIGNAL

ERROR: *** For bug report please send to developers:
ERROR: *** Log file: partition_test2_NOrev_allsamples.log

ERROR: *** Alignment files (if possible)
zsh: abort ./iqtree2 -s rev_allsamples.varsites.phy -p --model-joint 12.12 -B 1000 -T

I tried removing the -T AUTO but I get the same error

Thanks.

**Comment by KatherinOtalora** [comment]
I solved this by deleting the -p partition_test2_rev_allsamples.best_scheme.nex as in my case I have SNPs and the model could be GTR+ASC but the script hace model 12.12 so I don't need best_scheme.nex
