### ISSUE TITLE
ERROR: phylotreepars.cpp:63: void PhyloTree

### ISSUE THREAD

**Issue by sgarciah12** [iqtree/iqtree2#122]
Hello,

I am running IQ-TREE 2 in Linux with the following command for site-specific frequencies:
`iqtree2 -s COGs_155_concatenated.fasta -bb 1000 -alrt 1000 -T AUTO -ntmax 24 -m LG+F+R10+C20+PMSF -ft guide_tree.nwk`

And I get the following error:
```
Measuring multi-threading efficiency up to 24 CPU cores
ERROR: phylotreepars.cpp:63: void PhyloTree::computePartialParsimonyFast(PhyloNeighbor*, PhyloNode*): Assertion `!aln->ordered_pattern.empty()' failed.
ERROR: STACK TRACE FOR DEBUGGING:
ERROR: 1   funcAbort()
ERROR: 2   ()
ERROR: 3   gsignal()
ERROR: 4   abort()
ERROR: 12   PhyloTree::computeParsimonyBranchFast(PhyloNeighbor*, PhyloNode*, int*)
ERROR: 13   PhyloTree::setParsimonyBranchLengths()
ERROR: 14   PhyloTree::fixNegativeBranch(bool, Node*, Node*)
ERROR: 15   PhyloTree::wrapperFixNegativeBranch(bool)
ERROR: 16   PhyloTree::testNumThreads()
ERROR: 17   PhyloTree::ensureNumberOfThreadsIsSet(Params*)
ERROR: 18   computeSiteFrequencyModel(Params&, Alignment*)
ERROR: 19   runPhyloAnalysis(Params&, Checkpoint*, IQTree*&, Alignment*&)
ERROR: 20   runPhyloAnalysis(Params&, Checkpoint*)
ERROR: 21   main()
ERROR: 22   __libc_start_main()
ERROR: 23   _start()
ERROR: 
ERROR: *** IQ-TREE CRASHES WITH SIGNAL ABORTED
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: COGs_155_concatenated.fasta.log
```

I believe this error happens before the multi-core test, so it might have something to do with it, but I have no idea why.

The alignment used has 164 sequences with 46928 columns, 42201 distinct patterns

Version: IQ-TREE multicore version 2.2.2.2 COVID-edition for Linux 64-bit built Jan 13 2023

Find attached the log file.

Could you help me figure out what is the solution?

Best regards

Samuel
[COGs_155_concatenated.fasta.log](https://github.com/iqtree/iqtree2/files/10742939/COGs_155_concatenated.fasta.log)

**Comment by sgarciah12** [comment]
Hello @Z1-23, no, unfortunately I never found the solution to this bug. Let me know if you do!

**Comment by roblanf** [comment]
Hi @Z1-23 and @sgarciah12, can you try with `-T 1`, and then also with something more useful like `-T 8` or whatever makes sense for your situation. 

Sometimes if there's a bug in the threading it can simply be sidestepped by running the relevant part of the analysis on 1 thread.

This will help the developers (of which, sadly, I am not one) when they do get around to looking into this bug. So if you can report the results back here, that will also help. (Another thing that helps is to post the alignment that gives you the bug, without this it can be near impossible for us to recreate bugs).

**Comment by bqminh** [comment]
Please remove "+PMSF" from `-m LG+F+R10+C20+PMSF`. 
Moreover, I believe @roblanf pointed out the right solution, i.e., by specifying the thread number instead of AUTO. 
You can also check the latest version of IQ-TREE. I will close this issue now to clean up the issues. But if you see that the problem persists, feel free to reopen it.
