### ISSUE TITLE
weird example file default installation path

### ISSUE THREAD

**Issue by StephDC** [iqtree/iqtree2#124]
The `CMakeLists.txt` shows that the 4 example files shipped with this program would be installed to "."

https://github.com/iqtree/iqtree2/blob/master/CMakeLists.txt#L860-L863

However if a regular unix user attempt to cmake, make, make install, those 4 example files would ended up in `/usr` or `/usr/local` depending on my PREFIX, which is not the place those files belongs to, and could make the management of files a lot difficult.

I think the installation path for all of these files shall follow the convention, and changed to `share/doc/iqtree2/example` instead. I have created a fork with such modification, but I wonder if there is any second opinion, or if I should limit such modification to Unix only, or if there is anything else that I missed, before I open up a pull request for it.

**Comment by bqminh** [comment]
I normally run `make package`, that creates a zip or tar.gz file with the binaries and example files included. This ‘package’ file is then offered for download from www.iqtree.org<http://www.iqtree.org>. If you change these lines then it might mess up the package file.

If you have another way for make install, that wouldn’t intefere with make package, then I’m happy to review and probably merge it into the master branch.

Thanks!
Minh

On 17 Feb 2023, at 5:44 pm, Staph. aureus ***@***.***> wrote:



The CMakeLists.txt shows that the 4 example files shipped with this program would be installed to "."

https://github.com/iqtree/iqtree2/blob/master/CMakeLists.txt#L860-L863<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fiqtree%2Fiqtree2%2Fblob%2Fmaster%2FCMakeLists.txt%23L860-L863&data=05%7C01%7Cm.bui%40anu.edu.au%7C9b2de29a8b6647af1ce008db10b2780b%7Ce37d725cab5c46249ae5f0533e486437%7C0%7C0%7C638122130924107951%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Qy2lwSzhgqGH42ipHj2ohGPiPryarUG%2FhG8lMN6MGKk%3D&reserved=0>

However if a regular unix user attempt to cmake, make, make install, those 4 example files would ended up in /usr or /usr/local depending on my PREFIX, which is not the place those files belongs to, and could make the management of files a lot difficult.

I think the installation path for all of these files shall follow the convention, and changed to share/doc/iqtree2/example instead. I have created a fork with such modification, but I wonder if there is any second opinion, or if I should limit such modification to Unix only, or if there is anything else that I missed, before I open up a pull request for it.
