### ISSUE TITLE
taxon label length get shortened in output 

### ISSUE THREAD

**Issue by fulaibaowang** [iqtree/iqtree2#125]
Hi,

I noticed if I feed in an input with long taxon labels, it get shortened automatically in output.
Is there an option to prevent this?

Cheers,
Yun

**Comment by bqminh** [comment]
Can you give an example to be more specific? You can paste the WARNING printed in the log file.

I looked at the code and couldn't see a place where IQ-TREE truncates the labels. I can only see the code where IQ-TREE renames them if encountering any weird characters.
So I assume that you misunderstood it, but if it's not the case, feel free to reopen this issue.
