### ISSUE TITLE
Segfault/leak when analysing partitioned mixed data

### ISSUE THREAD

**Issue by arklumpus** [iqtree/iqtree2#129]
Hi! I am trying to analyse a partitioned mixed dataset (proteins + dna), but IQ-TREE v2.2.2.3 crashes just after starting the analysis.

Interestingly, v1.6.12 works fine, but v2.1.2, v2.1.3, and v2.2.0 instead of crashing start leaking memory (I stopped them when they got to 40GB with the dataset attached).

The error shown by v2.2.2.3 on screen is:

```
Error while parsing PHYLIP header (number of taxa and sequence length)
ERROR: STACK TRACE FOR DEBUGGING:
ERROR:
ERROR: *** IQ-TREE CRASHES WITH SIGNAL SEGMENTATION FAULT
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: partitions.nex.log
ERROR: ***    Alignment files (if possible)
Segmentation fault
```

The line talking about a PHYLIP header does not appear in the log file.

I can reproduce the issue with the attached minimal dataset. It contains four taxa, an amino acid alignment containing two aminoacids per taxon, a DNA alignment with two nucleotides per taxon, and the partition file specifying models for each. I am also attaching the log file.

I hope this is useful, please let me know if you need more information.

[partitions.zip](https://github.com/iqtree/iqtree2/files/11398161/partitions.zip)

**Comment by thomaskf** [comment]
Hi,

Thanks for reporting the issue. It has been fixed in version v.2.2.2.5, available at https://github.com/iqtree/iqtree2/releases .

Thomas

**Comment by arklumpus** [comment]
Thank you for fixing this so quickly! The new v2.2.2.5 works fine with my "full" dataset as well, so I'm closing the issue.
