### ISSUE TITLE
add Qmaker matrices to modelfinder

### ISSUE THREAD

**Issue by roblanf** [iqtree/iqtree2#15]
when I use modelfinder I would like Qplant, Qmammal, etc to be included when I select 'all' models.

**Comment by roblanf** [comment]
@bqminh is this done now? How about the nonrev models?

**Comment by bqminh** [comment]
will be released in v2.1.3: https://github.com/iqtree/iqtree2/releases/tag/v2.1.3 <https://github.com/iqtree/iqtree2/releases/tag/v2.1.3>
