### ISSUE TITLE
Update the FAQ for IQ-TREE on the website

### ISSUE THREAD

**Issue by fbartusch** [iqtree/iqtree2#150]
Dear IQ-TREE developers,

The FAQ on the website (http://www.iqtree.org/doc/Frequently-Asked-Questions) shows information for iqtree 1.x. Can you update it with the information for version 2?
I'm the admin of an HPC cluster and tried to help a user with his slow jobs. I trusted the information in the FAQ until I used the iqtree help function and found out, that the options `-nt` and `-ntmax` are only valid for iqtree 1.x.

Also I'm puzzled why the user's job runs when using an option that isn't valid any more. Maybe you can throw an error if `-nt` is used in iqtree 2.x?

Kind Regards,
Felix

**Comment by bqminh** [comment]
For backward compatibility, most, if not all, options in IQ-TREE 1 still work the same in IQ-TREE 2. We added new option to simplify the command, such as `-T` for `-nt`, but both are synonymous. So all good.
