### ISSUE TITLE
Tracking issue for IQtree segmentation fault issues

### ISSUE THREAD

**Issue by corneliusroemer** [iqtree/iqtree2#151]
I found a number of segmentation fault issues so thought I'll pull them into one place for ease of reference:
- https://github.com/iqtree/iqtree2/issues/145
- https://github.com/iqtree/iqtree2/issues/149
- https://github.com/iqtree/iqtree2/issues/12
- https://github.com/iqtree/iqtree2/issues/40
- https://github.com/iqtree/iqtree2/issues/123

There are two more issues that have been reported via nextstrain/augur's issue tracker:
- https://github.com/nextstrain/augur/issues/1338
- https://github.com/nextstrain/augur/issues/780

**Comment by wuyh0328** [comment]
I found that the software error at that time should be the reason why my file is too large, I later tried to extract a small part of the file, it can run successfully.

**Comment by wuyh0328** [comment]
So I did some filtering on my original file to make it a little smaller.

**Comment by bqminh** [comment]
Is it possible if any of you can test the latest version from https://github.com/iqtree/iqtree2/releases with these data again?
There have been several bug fixes in the mean time.

**Comment by thomaskf** [comment]
Some users have reported that the segmentation fault issues have been resolved. If there is any segmentation fault issue, please feel free to create a new issue because the situation is different every time. Now, this issue is closed.
