### ISSUE TITLE
Reuse models for partitions in concordance tutorial

### ISSUE THREAD

**Issue by aldendirks** [iqtree/iqtree2#155]
I'm wondering how to reuse models for partitions throughout the steps that are outlined in the concordance tutorial. http://www.iqtree.org/doc/Concordance-Factor

When inferring a species tree, all the work is done already to determine the best substitution models for the partitions (I have all my alignments in a directory so I'm using the -p flag). Between the output files `concat.best_model.nex` and `concat.best_scheme.nex` I figure there is the needed information to infer locus trees without running modelfinder again, which takes a long time on my dataset. 

The tutorial doesn't mention anything about reusing model informtion. It is redundant to rerun modelfinder when that information was just created for the species tree no? 

My species tree command was `$IQTREE2 -p $ALN_DIR -B 1000 -mset WAG,LG,JTT --prefix concat -T $CORES`. I tried the command `$IQTREE2 -S concat.best_scheme.nex --prefix loci -T $CORES` instead of `$IQTREE2 -S $ALN_DIR -mset WAG,LG,JTT --prefix loci -T $CORES` to infer gene trees and that seemed to work, but I'm not sure if there is a good reason not to reuse model information between inferring the species tree and gene trees. 

Thanks for your help!

**Comment by bqminh** [comment]
Your command with `-S concat.best_scheme.nex` looks good to me. 
You can even make it faster by replacing it with `-S concat.best_model.nex`, because this best_model file contain the model parameters that IQ-TREE will use. Whereas the best_scheme file doesn't have the parameter values and IQ-TREE will have to reestimate them again.
