### ISSUE TITLE
11 weight for 12.12 model & rate parameters for each site

### ISSUE THREAD

**Issue by kurohuji** [iqtree/iqtree2#158]
I am trying to generate array data by simulation and have three questions about AliSim.

(1) What do the each 11 weight parameters in the 12.12 model control?
(2) Can I directly control the rate parameter R?
(3) Can I get the evolution rate for each site when I introduce rate heterogeneity across sites with +GC, +G. +R?

Thank you.

**Comment by trongnhanuit** [comment]
Dear Kurohuji,
Thank you for using AliSim. Please find my answers below.


> *(1) What do the each 11 weight parameters in the unrest model control?*

=> Each parameter specifies the rate at which one nucleotide evolves to
another one with the order as follows.
[image: image.png]


>
> *(2) Can I directly control the rate parameter R?*

=> Yes, you can specify the rates and weights for different rate categories
of the FreeRate model. Please have a look at *HERE
<http://www.iqtree.org/doc/Substitution-Models#dna-models:~:text=might%20be%20overestimated.-,Rate%20heterogeneity%20across%20sites,-IQ%2DTREE%20supports>*

*(3) Can I get the evolution rate for each site when I introduce rate
> heterogeneity across sites with +GC, +G. +R?*

=> Sorry, AliSim currently doesn't output the rate of each site.

Hope it is helpful. Please feel free to contact us if you have any
questions.


Cheers,
Nhan

**Comment by kurohuji** [comment]
Thank you for your response.

> => Each parameter specifies the rate at which one nucleotide evolves to
another one with the order as follows.
[image: image.png]

I was unable to view image.png.

> => Yes, you can specify the rates and weights for different rate categories
of the FreeRate model. Please have a look at *HERE

The link mentioned common DNA models "The last column Code is a 6-digit code defining the equality constraints for 6 relative substitution rates: A-C, A-G, A-T, C-G, C-T and G-T". However, there was no description of unrestricted models.

**Comment by trongnhanuit** [comment]
Hi Kurohuji,


> *(1) What do the each 11 weight parameters in the unrest model control?*

=> Each parameter specifies the rate at which one nucleotide evolves to
another one with the order as follows.

Param Substitution Notes
1 A->C
2 A->G
3 A->T
4 C->A
5 C->G
6 C->T
7 G->A
8 G->C
9 G->T
10 T->A
11 T->C
12 T->G = 1


> *(2) Can I directly control the rate parameter R?*

=> Yes, you can specify the rates and weights for different rate categories
of the FreeRate model. Please have a look at
http://www.iqtree.org/doc/Substitution-Models#rate-heterogeneity-across-sites
<http://www.iqtree.org/doc/Substitution-Models#rate-heterogeneity-across-sites>

*"Users can fix the parameters of the model. For example, +I{0.2} will fix
> the proportion of invariable sites (pinvar) to 0.2; +G{0.9} will fix the
> Gamma shape parameter (alpha) to 0.9; +I{0.2}+G{0.9} will fix both pinvar
> and alpha. To fix the FreeRate model parameters, use the
> syntax +Rk{w1,r1,...,wk,rk} (replacing k with the number of categories).
> Here, w1, ..., wk are the weights and r1, ..., rk the rates for each
> category."*

**Comment by kurohuji** [comment]
Thank you for your response.

>  *(2) Can I directly control the rate parameter R?*
=> Yes, you can specify the rates and weights for different rate categories
of the FreeRate model. Please have a look at
http://www.iqtree.org/doc/Substitution-Models#rate-heterogeneity-across-sites
<http://www.iqtree.org/doc/Substitution-Models#rate-heterogeneity-across-sites>

I apologize for the my confusing writing.
Here, R I written was not about R specify site-to-site speed variation.
If I generate an array using the UNREST model with iqtree2 --alisim, I will get the following output (alignment_xxx.log).

```
IQ-TREE multicore version 2.2.2.6 COVID-edition for Windows 64-bit built May 27 2023
Developed by Bui Quang Minh, James Barbetti, Nguyen Lam Tung,
Olga Chernomor, Heiko Schmidt, Dominik Schrempf, Michael Woodhams, Ly Trong Nhan.

. . .

SUBSTITUTION PROCESS
--------------------

Model of substitution: 12.12

Rate parameter R: <=

  A-C: 0.500
  A-G: 2.000
  A-T: 0.500
  C-A: 0.500
  C-G: 0.500
  C-T: 2.000
  G-A: 2.000
  G-C: 0.500
  G-T: 0.500
  T-A: 0.500
  T-C: 2.000
  T-G: 0.500

. . .
```
I would like to specify this R directly; from reading the answer to the first question it seems that is possible. 

> *(1) What do the each 11 weight parameters in the unrest model control?*
=> Each parameter specifies the rate at which one nucleotide evolves to
> another one with the order as follows.
> 
> Param Substitution Notes
> 1 A->C
> 2 A->G
> 3 A->T
> 4 C->A
> 5 C->G
> 6 C->T
> 7 G->A
> 8 G->C
> 9 G->T
> 10 T->A
> 11 T->C
> 12 T->G = 1

However, if I actually pass any parameter to the UNREST model, the value of R simply does not match.

```
iqtree2 --alisim alignment -m 12.12{0.9/1.1/0.8/1.2/0.7/1.3/0.6/1.4/0.5/1.5/0.4} -t RANDOM{bd{0.95/0.05}/4} -redo
. . .
ERROR: Weights for Lie Markov model must be between -0.98 and 0.98
```

```
iqtree2 --alisim alignment -m 12.12{0.0/0.0/0.0/0.0/0.0/0.0/0.0/0.0/0.0/0.0/0.0} -t RANDOM{bd{0.95/0.05}/4} -redo
. . .
Rate parameter R:

  A-C: 1.000
  A-G: 1.000
  A-T: 1.000
  C-A: 1.000
  C-G: 1.000
  C-T: 1.000
  G-A: 1.000
  G-C: 1.000
  G-T: 1.000
  T-A: 1.000
  T-C: 1.000
  T-G: 1.000
```

```
iqtree2 --alisim alignment -m 12.12{-0.5/-0.5/-0.5/-0.5/-0.5/-0.5/-0.5/-0.5/-0.5/-0.5/-0.5} -t RANDOM{bd{0.95/0.05}/4} -redo
. . .
Rate parameter R:

  A-C: 1.100
  A-G: 0.700
  A-T: 1.500
  C-A: 0.700
  C-G: 1.100
  C-T: 1.100
  G-A: 0.500
  G-C: 0.900
  G-T: 1.300
  T-A: 1.300
  T-C: 0.900
  T-G: 0.900
```

```
iqtree2 --alisim alignment -m 12.12{0.5/0.0/0.0/0.0/0.0/0.0/0.0/0.0/0.0/0.0/0.0} -t RANDOM{bd{0.95/0.05}/4} -redo
. . .
Rate parameter R:

  A-C: 0.500
  A-G: 2.000
  A-T: 0.500
  C-A: 0.500
  C-G: 0.500
  C-T: 2.000
  G-A: 2.000
  G-C: 0.500
  G-T: 0.500
  T-A: 0.500
  T-C: 2.000
  T-G: 0.500
```

```
iqtree2 --alisim alignment -m 12.12{0.0/0.5/0.0/0.0/0.0/0.0/0.0/0.0/0.0/0.0/0.0} -t RANDOM{bd{0.95/0.05}/4} -redo
. . .
Rate parameter R:

  A-C: 1.500
  A-G: 1.000
  A-T: 0.500
  C-A: 1.500
  C-G: 0.500
  C-T: 1.000
  G-A: 1.000
  G-C: 0.500
  G-T: 1.500
  T-A: 0.500
  T-C: 1.000
  T-G: 1.500
```

**Comment by trongnhanuit** [comment]
Hi Kurohuji,
I found that you're specifying the wrong model name. 12.12 is a Lie-Markov
model, which is equivalent, but the meaning of the parameters is different
from those of the UNREST model.
Please try with, e.g.,

iqtree2 --alisim alignment -m
UNREST{0.9/1.1/0.8/1.2/0.7/1.3/0.6/1.4/0.5/1.5/0.4} -t
RANDOM{bd{0.95/0.05}/4} -redo

Thanks
Nhan

**Comment by kurohuji** [comment]
Resolved.
Thank you very much.
