### ISSUE TITLE
IQ-TREE not working on M1 macbook

### ISSUE THREAD

**Issue by arthurltaylor** [iqtree/iqtree2#159]
I have put iqtree and iqtree2 in the usr/local/bin folder and tried to run both

`iqtree -s /Users/arthur/Desktop/18salignment3.phy -w /Users/arthur/Desktop `
to return:
`zsh: bad CPU type in executable: iqtree`
and

`iqtree2 -s /Users/arthur/Desktop/18salignment3.phy -w /Users/arthur/Desktop`
to return:
`zsh: bad CPU type in executable: iqtree2`

Is IQ-TREE not compatible with my new computer?

I was happy using it on my 8 year old macbook until I got this error:
`NOTE: ModelFinder requires 12337 MB RAM!
ERROR: Memory required exceeds your computer RAM size!
`

So, are both my computers unable to complete the task?

**Comment by corneliusroemer** [comment]
Have you installed Rosetta? Until very recently, mac executables required rosetta 2 to run on arm macs.
