### ISSUE TITLE
Iqtree2 covid19 version

### ISSUE THREAD

**Issue by sanjusare** [iqtree/iqtree2#16]
Dear Bui Quang Minh,

I was trying to use the windows version of IQtree2 for COVID-19 (iqtree-2.1.2-Windows), but the run finished after the evaluation of identical sequences.
I am attaching the log file created.
[all_30-11-20_2.fas_UnAmbigu.fasta.log](https://github.com/iqtree/iqtree2/files/5691786/all_30-11-20_2.fas_UnAmbigu.fasta.log)

Do you have an idea of what is wrong?,

Thank you very much in advance for your prompt answer.

**Comment by bqminh** [comment]
I'm pretty sure this SARS-Cov-2 dataset with >100K sequences (from the log):

```
Alignment has 109953 sequences with 29472 columns, 18340 distinct patterns
```

is too big for IQ-TREE! However, the good news is v2.3.4.cmaple now provides option `--pathogen` to work exactly on this kind of data. Please see the document: 

http://www.iqtree.org/doc/Command-Reference#tree-search-for-pathogen-data
