### ISSUE TITLE
IQTree crashes with nonreversible models

### ISSUE THREAD

**Issue by brj1** [iqtree/iqtree2#162]
I am trying to use ancestral sequence reconstruction in IQ-TREE (version 2.2.2.7 COVID-edition for Mac OS X 64-bit built May 30 2023) on fixed trees with non-reversible Lie Markov models. I am using the following command on an M2 Mac Book Pro:

```
iqtree -st DNA -s Z1165M/aligned/Z1165M_latent_tree_reflen_al.fasta -te Z1165M/root/Z1165M_latent_tree_rootwithogr.nwk -asr -pre Z1165M/ancest/iqtree/Z1165M_latent_tree_nonrev_withogr -m MFP -mset liemarkov -nt 1 -redo -keep_empty_seq
```

However, for some of my data sets IQ-TREE crashes. See log file:

[Z1165M_latent_tree_rev_withogr.log](https://github.com/iqtree/iqtree2/files/14273168/Z1165M_latent_tree_rev_withogr.log)

Alignment and fixed tree attached:

[Z1165M_latent_tree_reflen_al.fasta.zip](https://github.com/iqtree/iqtree2/files/14273178/Z1165M_latent_tree_reflen_al.fasta.zip)
[Z1165M_latent_tree_rootwithogr.nwk.zip](https://github.com/iqtree/iqtree2/files/14273189/Z1165M_latent_tree_rootwithogr.nwk.zip)

It seems to be caused by numerical instability. If I run the same command on the latest version 1 of IQ-TREE (version 1.6.12 for Mac OS X 64-bit built Aug 15 2019), I do not encounter any errors and IQ-TREE completes.

**Comment by JGLAHE** [comment]
From the bottom of you logfile:
```
Analysis results written to: 
  IQ-TREE report:                Z1165M/ancest/iqtree/Z1165M_latent_tree_rev_withogr.iqtree
  Maximum-likelihood tree:       Z1165M/ancest/iqtree/Z1165M_latent_tree_rev_withogr.treefile
  Ancestral state:               Z1165M/ancest/iqtree/Z1165M_latent_tree_rev_withogr.state
  Screen log file:               Z1165M/ancest/iqtree/Z1165M_latent_tree_rev_withogr.log

Date and Time: Tue Jan 30 15:27:09 2024
```
This job completed successfully, writing your .state file `Z1165M_latent_tree_rev_withogr.state`

The line:
```
WARNING: Estimated model parameters are at boundary that can cause numerical instability!
```
is just a warning, which in your case wasn't followed by an actual crash, which usually looks like:
```
ERROR: *** IQ-TREE CRASHES WITH SIGNAL SEGMENTATION FAULT
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: tmp.aln.log
ERROR: ***    Alignment files (if possible)
Segmentation fault (core dumped)
```
The warning was probably triggered by some of your rate parameters being >=100 (see [this discussion](https://groups.google.com/g/iqtree/c/hfKsERj6A5c)). See your IQ-TREE report Z1165M/ancest/iqtree/Z1165M_latent_tree_rev_withogr.iqtree, which should contain something like this:
```
Rate parameter R:

  A-C: 21.6058
  A-G: 100.0000
  A-T: 21.6058
  C-G: 1.0000
  C-T: 100.0000
  G-T: 1.0000
```
Note: underflow *can* actually crash the job. Using the option `-safe` (IQ-TREE v1 & v2.x) or `--safe` (IQ-TREE v2.x) in the iqtree command generally prevents this (depending on the IQ-TREE version), except in the case of non-reversible models (this has been fixed in [v2.2.6](https://github.com/iqtree/iqtree2/releases/tag/v2.2.6)).

**Comment by brj1** [comment]
Sorry, I attached the wrong log file (The alignment and tree file are correct). Below is the correct one.

[Z1165M_latent_tree_nonrev_withogr.log](https://github.com/iqtree/iqtree2/files/14303300/Z1165M_latent_tree_nonrev_withogr.log)

IQTree was crashing with:

```
ERROR: ratefree.cpp:556: double RateFree::optimizeWithEM(): Assertion `score > old_score-0.1' failed.
ERROR: STACK TRACE FOR DEBUGGING:
ERROR: 2   _sigtramp()
ERROR: 3   __d2b_D2A()
ERROR: 5   RateFree::optimizeWithEM() (.cold.3)
ERROR: 6   RateFree::optimizeWithEM()
ERROR: 7   RateFree::optimizeParameters(double)
ERROR: 8   ModelFactory::optimizeParameters(int, bool, double, double)
ERROR: 9   CandidateModel::evaluate(Params&, ModelCheckpoint&, ModelCheckpoint&, ModelsBlock*, int&, int)
ERROR: 10   CandidateModelSet::test(Params&, PhyloTree*, ModelCheckpoint&, ModelsBlock*, int, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool)
ERROR: 11   runModelFinder(Params&, IQTree&, ModelCheckpoint&)
ERROR: 12   startTreeReconstruction(Params&, IQTree*&, ModelCheckpoint&)
ERROR: 13   runPhyloAnalysis(Params&, Checkpoint*, IQTree*&, Alignment*&)
ERROR: 14   runPhyloAnalysis(Params&, Checkpoint*)
ERROR: 
ERROR: *** IQ-TREE CRASHES WITH SIGNAL ABORTED
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: Z1165M/ancest/iqtree/Z1165M_latent_tree_nonrev_withogr.log
ERROR: ***    Alignment files (if possible)
```

However, I tried adding the --safe parameter and iqtree was able to complete.

**Comment by JGLAHE** [comment]
I've never used Rev. Lie-Markov so don't how how it behaves, but I just noticed you've also got ambiguous characters just within the `REF...` sequence; you've also got a stop codon at the end of the alignment...no idea what effects that has (you've obviously worked something out)
