### ISSUE TITLE
crashing during model selection

### ISSUE THREAD

**Issue by fvfreitas** [iqtree/iqtree2#163]
Dear colleagues,

I am analyzing a large matrix of UCEs using the partitioning scheme resulting from SWSC-EN (Tagliacollo & Lanfear 2018) in the latest version of iqtree (2.2.2.7) available. I ran it with the MFP+MERGE option so it would run PartitionFinder2 to merge the small partitions proposed by the previously mentioned strategy and then run a model search. It concludes the merging step, but during the model search, it crashes and gives me the following error:
`ERROR: ratefree.cpp:556: double RateFree::optimizeWithEM(): Assertion score > old_score-0.1 failed.`

Thanks,
Felipe.

**Comment by thomaskf** [comment]
Dear Felipe,

Thanks for reporting the issue. In order to understand the problem, is it
possible to send us the alignment file, the partition scheme, and the log
file so that we can check the issue? You can send them to us via email. I
appreciate your help. Thank you very much.

Thomas

**Comment by thomaskf** [comment]
Dear all,

This issue has been addressed in the version 2.3.1 or later (https://github.com/iqtree/iqtree2/releases).
Thank you.

Thomas
