### ISSUE TITLE
`--tree-fix` flag throws error "Invalid option"

### ISSUE THREAD

**Issue by sjspielman** [iqtree/iqtree2#17]
Hi, 

I'm trying to using iqtree2  to optimize branch lengths on a fixed topology, but encounter the error `Invalid "--tree-fix" option.` when using the `--tree-fix` flag described in the help menu. Can you clarify what flag should be used?

Version:
```
IQ-TREE multicore version 2.1.2 COVID-edition for Mac OS X 64-bit built Oct 22 2020
Developed by Bui Quang Minh, James Barbetti, Nguyen Lam Tung,
Olga Chernomor, Heiko Schmidt, Dominik Schrempf, Michael Woodhams.
```

Help menu says:
`--tree-fix           Fix -t tree (no tree search performed)`

Reproducible example:
`iqtree2 -m LG -s data.fasta -t data.tre --tree-fix`

I have attached the data files from example. 

Thanks!
-Stephanie
[forissue.zip](https://github.com/iqtree/iqtree2/files/5777068/forissue.zip)

**Comment by sjspielman** [comment]
Hi, wanted to send a quick update. I came back to this and tried using the `-te` flag instead of `-t` and without `--tree-fix` to try and fix the tree, but the topology was still optimized.

**Comment by bqminh** [comment]
Hi Stephanie,

--tree-fix option is not properly handled. Thanks for pointing this out!

For now please use -te TREE_FILE option.

Thanks
Minh

**Comment by sjspielman** [comment]
Hi @bqminh , 

Thanks for having a look! Tried again with `-te`, and it **does** seem to be working - reasonably sure my previous comment about `-te` was wrong (there was a polytomy in my original tree that I didn't notice, so all good!).

Thanks, 
Stephanie
