### ISSUE TITLE
Cannot find exact build setup used to make the release binaries

### ISSUE THREAD

**Issue by corneliusroemer** [iqtree/iqtree2#171]
I had a look but couldn't find a build script that you use to produce the Github release assets = binaries.

The documentation is very out of date (e.g. referring to clang-3.7, when we're currently on version 17). It would be great if builds could run in CI as well, then it's reproducible for everyone.

**Comment by thomaskf** [comment]
Thanks for your suggestion. The compilation guide has been updated. Thanks.
