### ISSUE TITLE
Compliation error

### ISSUE THREAD

**Issue by ajithperera** [iqtree/iqtree2#179]
Hello: I am trying to install iq-tree/2.3.2 on X86_64 (RHEL8) with gcc/12.2.0 openmpi/4.1.5. I have compilation error 
/dist/apps/iq-tree/2.3.2/model/modelmarkov.cpp:26:10: fatal error: Eigen/EigenSolver: No such file or directory
   26 | #include <Eigen/EigenSolver>

I have eigen3/3.4.0 installed.    I have specified -DEIGEN3_INCLUDE_DIR=xxx/xxx.eigen3/3.4.0 (where xxx/xxx are system-dependent paths).  I do not have any file named EigenSolver. However, I see EigenSolver.h in /xxx/xxx/eigen3/3.4.0/Eigen/src/Eigenvalues. 

Shouldn't this be changed? 

Thanks, Ajith

**Comment by thomaskf** [comment]
Hi,

Can you please compile the codes using gcc 10 or clang?

Thanks,
Thomas

**Comment by thomaskf** [comment]
Hi,

When using gcc newer than v10, you must set the following variable while compiling IQ-TREE source codes.
`export CXXFLAGS="-std=c++14"`

You may refer to the ci.yaml file for details: https://github.com/iqtree/iqtree2/blob/master/.github/workflows/ci.yaml. Thanks, @martin-g, for this information.

Thomas

**Comment by ajithperera** [comment]
Thanks. I used export CXXFLAGS="-std=c++14" before starting this thread. 

I believe model/modelmarkov.cpp, #include <Eigen/EigenSolver> to be corrected as #include <Eigen/Eigenvalues> because there is no file called EigenSolver in eigen3.  The current version of eigen3 (3.4.0) installation eigen3/3.4.0/include/eigen3/Eigen3 has the file "Eigenvalues" which then include Eigensolver.h (see below). With this change and setting -DEIGEN3_INCLUDE_DIR= /apps/eigen3/3.4.0/include/eigen3, the code compiles and runs the test (example.phy) successfully (despite many warnings; I have not carefully analyzed the warnings.), 

I believe the code and the instructions to set eigen3 dir need to change to match with the current organization of eigen3.

// This file is part of Eigen, a lightweight C++ template library
// for linear algebra.
//
// This Source Code Form is subject to the terms of the Mozilla
// Public License v. 2.0. If a copy of the MPL was not distributed
// with this file, You can obtain one at http://mozilla.org/MPL/2.0/.

#ifndef EIGEN_EIGENVALUES_MODULE_H
#define EIGEN_EIGENVALUES_MODULE_H

#include "Core"

#include "Cholesky"
#include "Jacobi"
#include "Householder"
#include "LU"
#include "Geometry"

#include "src/Core/util/DisableStupidWarnings.h"

/** \defgroup Eigenvalues_Module Eigenvalues module
  *
  *
  *
  * This module mainly provides various eigenvalue solvers.
  * This module also provides some MatrixBase methods, including:
  *  - MatrixBase::eigenvalues(),
  *  - MatrixBase::operatorNorm()
  *
  * \code
  * #include <Eigen/Eigenvalues>
  * \endcode
  */

#include "src/misc/RealSvd2x2.h"
#include "src/Eigenvalues/Tridiagonalization.h"
#include "src/Eigenvalues/RealSchur.h"
#include "src/Eigenvalues/EigenSolver.h"
#include "src/Eigenvalues/SelfAdjointEigenSolver.h"
#include "src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h"
#include "src/Eigenvalues/HessenbergDecomposition.h"
#include "src/Eigenvalues/ComplexSchur.h"
#include "src/Eigenvalues/ComplexEigenSolver.h"
#include "src/Eigenvalues/RealQZ.h"
#include "src/Eigenvalues/GeneralizedEigenSolver.h"
#include "src/Eigenvalues/MatrixBaseEigenvalues.h"
#ifdef EIGEN_USE_LAPACKE
#ifdef EIGEN_USE_MKL
#include "mkl_lapacke.h"
#else
#include "src/misc/lapacke.h"
#endif
#include "src/Eigenvalues/RealSchur_LAPACKE.h"
#include "src/Eigenvalues/ComplexSchur_LAPACKE.h"
#include "src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h"
#endif

#include "src/Core/util/ReenableStupidWarnings.h"

#endif // EIGEN_EIGENVALUES_MODULE_H

**Comment by martin-g** [comment]
How do you provide/install `eigen3` ?
The CI runs on Ubuntu and installs `libeigen3-dev (3.4.0-2ubuntu2)` and all is fine - https://productionresultssa15.blob.core.windows.net/actions-results/8d120be9-d1fa-4c3a-8274-67d45f2a5cf4/workflow-job-run-2bed76c1-78c9-59bd-4cfa-7ea0a3ee4176/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-05-06T06%3A52%3A57Z&sig=Q9A9PR3Pfdn0dm23p0xB993P3ZnQnLNeIdnRfWNsKZc%3D&sp=r&spr=https&sr=b&st=2024-05-06T06%3A42%3A52Z&sv=2021-12-02

See https://github.com/iqtree/iqtree2/blob/c665a53004cb2c07f77558ff6883dd6d63b82ae9/.github/workflows/ci.yaml#L22

**Comment by martin-g** [comment]
On RHEL-like Linuxes you need `eigen3-devel` package.
I am able to build iqtree2 on my openEuler 22.03 LTS SP3 ARM64 machine with similar steps as the one in the Github Actions workflow.
There I use `eigen3-devel.noarch   3.3.8-4.oe2203sp3`, i.e. v. 3.3.8

**Comment by bqminh** [comment]
I assume this issue is resolved now.
