### ISSUE TITLE
Limit fast initial parsimony tree by random order stepwise addition

### ISSUE THREAD

**Issue by Steven-Kemp** [iqtree/iqtree2#18]
Is it possible to limit the number of threads that the computer/cluster uses to build the initial parsimony tree at all?

When I send a job with e.g. -T AUTO, IQTREE2 will utilise all available threads, which takes an infinitely long amount of time for the first stage. What I need it to do is analyse the best number of threads for downstream analysis, and then use the same number of threads for all stages.

Does that make sense?

Best wishes,
Steve

**Comment by bqminh** [comment]
Hi Steve, this is a known issue, but there is a workaround. You need to manually set the OMP_NUM_THREADS environment variable. Under Linux, some command line like:

```
OMP_NUM_THREADS=1 iqtree2 ...
```

will do the trick. Without defining OMP_NUM_THREADS, all CPU cores will be used. You can increase 1 to higher value but observe how faster (or even slower) it gets. IQ-TREE is just unable to estimate the number of threads for parsimony construction.

Once the initial parsimony tree is finished, IQ-TREE will be able to estimate the optimal number of threads and override the OMP_NUM_THREADS parameter.

**Comment by Steven-Kemp** [comment]
Hi Bui,

Seems to be working for me, thanks so much!

**Comment by joelnitta** [comment]
This also solves the same problem for me, but I'm wondering if it should really be considered closed since it's a work-around external to IQTREE: I think the real solution would be a fix within IQTREE so the user doesn't have to set OMP_NUM_THREADS?
