### ISSUE TITLE
SIGNAL SEGMENTATION FAULT

### ISSUE THREAD

**Issue by OliveiraDS-hub** [iqtree/iqtree2#184]
I have an alignment with ~2600 sequences, running in a machine with 32 threads and 160Gb RAM.

I'm getting the SIGNAL SEGMENTATION FAULT error, but it doesn't seem lack of memory.

I have tried with iqtree version 1.6.3 and 2.1.4.

2751  SRR17577079          0.00%    passed    100.00%
****  TOTAL                0.21%  2 sequences failed composition chi2 test (p-value<5%; df=19)
NOTE: minimal branch length is reduced to 0.000000064554 for long alignment
NOTE: SRR9645764 is identical to SRR10461263 but kept for subsequent analysis
NOTE: ERR6001614 is identical to ERR11173242 but kept for subsequent analysis
NOTE: SRR7909414 is identical to SRR12784142 but kept for subsequent analysis
ERROR: STACK TRACE FOR DEBUGGING:
ERROR: 1   funcAbort()
ERROR: 2   ()
ERROR: 3   pllLoadAlignment()
ERROR: 4   IQTree::initializePLL(Params&)
ERROR: 5   startTreeReconstruction(Params&, IQTree*&, ModelCheckpoint&)
ERROR: 6   runPhyloAnalysis(Params&, Checkpoint*)
ERROR: 7   main()
ERROR: 8   __libc_start_main()
ERROR: 9   _start()
ERROR:
ERROR: *** IQ-TREE CRASHES WITH SIGNAL SEGMENTATION FAULT
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: AURISMAR2.fas.log
ERROR: ***    Alignment files (if possible)

I would like to know if there is a way to avoid this error.

Thank you in advance

**Comment by thomaskf** [comment]
Hi Daniel,
Thanks for reporting the issue.
Can you test it by using version 2.3.4 at
https://github.com/iqtree/iqtree2/releases?
Several issues have been resolved since 2.1.4, and some of them were
related to segmentation faults.
Thanks,
Thomas

**Comment by OliveiraDS-hub** [comment]
Dear @thomaskf 
Indeed, using the version 2.3.4 the analysis has been done without any segmentation faults error.

Thank you!
