### ISSUE TITLE
Error with the constrained tree search

### ISSUE THREAD

**Issue by chainorato** [iqtree/iqtree2#197]
Hi,

Thank you for your previous help with the latest issue (issue: 180).
However, I'm sorry for bothering you again. I found another issue with constrained tree search.

I used IQ-TREE v.2.3.4 with the following code for the constrained tree search.
`iqtree2 -s GeneID_9960_USP3.trimal -g GeneID_9960_USP3/GeneID_9960_USP3.const.sp_tree.treefile -m MFP  -B 1000 -alrt 1000 -T 1 -mem 16G`

Here's the error I found.
```
NOTE: XP_024853354.1 is identical to XP_019824270.1 but kept for subsequent analysis
NOTE: XP_043774835.1 is identical to XP_043327665.1 but kept for subsequent analysis
NOTE: XP_027425016.1 is identical to XP_027956068.1 but kept for subsequent analysis
NOTE: XP_014997844.1 is identical to XP_045253218.1 but kept for subsequent analysis
NOTE: XP_034849969.1 is identical to XP_054369458.1 but kept for subsequent analysis
NOTE: XP_042844626.1 is identical to XP_042797721.1 but kept for subsequent analysis
NOTE: XP_040348850.1 is identical to XP_025774983.1 but kept for subsequent analysis
NOTE: XP_040499073.1 is identical to XP_026334047.1 but kept for subsequent analysis
NOTE: 2 identical sequences (see below) will be ignored for subsequent analysis
NOTE: XP_050651921.1 (identical to XP_045253218.1) is ignored but added at the end
NOTE: XP_049467679.1 (identical to XP_042797721.1) is ignored but added at the end
2 taxa removed from constraint tree
Alignment was printed to GeneID_9960_USP3.trimal.uniqueseq.phy

For your convenience alignment with unique sequences printed to GeneID_9960_USP3.trimal.uniqueseq.phy

WARNING: Rooted constraint tree will be treated as unrooted tree
ERROR: ERROR: Taxon XP_049467679.1 in constraint tree does not appear in full tree
ERROR: ERROR: Taxon XP_050651921.1 in constraint tree does not appear in full tree
ERROR: Bad constraint tree (see above)
```

I've compared the result with another gene (GeneID_167359_NIM1K) that lacks an issue.
The tree was successfully reconstructed. Here's the message IQ-TREE reported.
```
WARNING: Rooted constraint tree will be treated as unrooted tree
INFO: Constraint tree will be applied to ML tree and all bootstrap trees.
NOTE: XP_032327540.1 is identical to XP_010964624.1 but kept for subsequent analysis
NOTE: XP_008535326.1 is identical to XP_001498479.1 but kept for subsequent analysis
NOTE: XP_027462966.1 is identical to XP_027953917.1 but kept for subsequent analysis
NOTE: NP_001253575.1 is identical to XP_005556887.2 but kept for subsequent analysis

WARNING: Rooted constraint tree will be treated as unrooted tree
Creating fast initial parsimony tree by random order stepwise addition...
WARNING: Constraint tree has all taxa and is bifurcating, which strictly enforces final tree!
0.003 seconds, parsimony score: 0 (based on 857 sites)
```

The problem for GeneID_9960 seems to be caused by removing the two identical sequences.
```
NOTE: XP_050651921.1 (identical to XP_045253218.1) is ignored but added at the end
NOTE: XP_049467679.1 (identical to XP_042797721.1) is ignored but added at the end
2 taxa removed from constraint tree
```
I do not understand why they were ignored by IQ-TREE whereas the other identical sequences were kept.

Could you suggest me how should I cope with this problem?
I've attached data on the tree with the issue (GeneID_9960_USP3) and the another one without the issue (GeneID_167359_NIM1K) for comparison.

[GeneID_9960_USP3_v2.3.4.tar.gz](https://github.com/iqtree/iqtree2/files/15317056/GeneID_9960_USP3_v2.3.4.tar.gz)
[GeneID_167359_NIM1K_v2.3.4.tar.gz](https://github.com/iqtree/iqtree2/files/15316994/GeneID_167359_NIM1K_v2.3.4.tar.gz)

Thank you in advance!

**Comment by chainorato** [comment]
Hi @thomaskf

I have just understood how IQ-TREE treats identical sequences.
[http://www.iqtree.org/doc/Frequently-Asked-Questions#how-does-iq-tree-treat-identical-sequences]

After I tried adding `--keep-ident` to my code, the program worked fine. This seems to solve the current problem.

The additional changes I did are removing node labels in the constraint tree and removing branch support calculation options `-B 1000 -alrt 1000`. However, I don't think they affect the issue.

Here's the result I have gotten, just in case you want to figure out the issue more.
[GeneID_9960_USP3_v2.3.4_keep_ident.tar.gz](https://github.com/iqtree/iqtree2/files/15398108/GeneID_9960_USP3_v2.3.4_keep_ident.tar.gz)

Thank you so much for taking a look!

**Comment by roblanf** [comment]
@thomaskf one suggestion (because this is an issue that hits a lot of people) would be that if someone uses a constrained tree search we put `--keep-ident` on by default, and print an INFO message about that. 

Even better if we cross-check to see if any sequences identified as identical are in the constrained tree, and only then force `--keep-ident` to be on (with an INFO message again).

**Comment by thomaskf** [comment]
@chainorato Thanks for reporting the issue. Yes, adding --keep-ident is a good solution. 
The fix to this issue has been uploaded to the master branch, and it will be included in our next release. 
The option --keep-ident will be forced to be on when the constrained tree is set.  @roblanf Thanks for the suggestion.
Now I close the issue.

**Comment by SethMusker** [comment]
The same error occurs when supplying a starting tree with -t and there are non-unique sequences. I opened an issue at https://github.com/iqtree/iqtree3/issues/82

**Comment by thomaskf** [comment]
@SethMusker Thanks for reporting the issue. Do you mind sending us the data so that we can look into the issue? You may send the data to me directly to thomaskf@gmail.com . Many thanks!
