### ISSUE TITLE
Process stuck in INITIALIZING CANDIDATE TREE SET

### ISSUE THREAD

**Issue by OliveiraDS-hub** [iqtree/iqtree2#204]
Dear developer, I'm struggling for ~12 days with a stuck process using IQtree 2.3.4.

Basically, I have an alignment with ~2600 sequences, running in a machine with 32 threads and 160Gb RAM. The whole process goes smoothly until the step "INITIALIZING CANDIDATE TREE SET"

This is the last 50 lines of my log file:

>****  TOTAL                0.21%  2 sequences failed composition chi2 test (p-value<5%; df=19)
NOTE: minimal branch length is reduced to 0.000000064554 for long alignment
NOTE: SRR9645764 is identical to SRR10461263 but kept for subsequent analysis
NOTE: ERR6001614 is identical to ERR11173242 but kept for subsequent analysis
NOTE: SRR7909414 is identical to SRR12784142 but kept for subsequent analysis

>CHECKPOINT: Initial tree restored
Generating 1000 samples for ultrafast bootstrap (seed: 485483)...

>NOTE: 81875 MB RAM (79 GB) is required!
WARNING: Memory required per CPU-core (4.99731 GB) is higher than your computer RAM per CPU-core (4 GB), thus multiple runs may exceed RAM!
Estimate model parameters (epsilon = 0.100)
>1. Initial log-likelihood: -27028094.098
WARNING: Numerical underflow for lh-derivative
Optimal log-likelihood: -27008668.780
Parameters optimization took 1 rounds (1748.341 sec)
Wrote distance file to...
Computing ML distances based on estimated model parameters...
Calculating distance matrix: done in 746.899 secs using 1599% CPU
Computing ML distances took 757.799666 sec (of wall-clock time) 12066.986825 sec (of CPU time)
Setting up auxiliary I and S matrices: done in 0.18691 secs using 183.4% CPU
Computing RapidNJ tree took 3.336899 sec (of wall-clock time) 6.399685 sec (of CPU time)
Log-likelihood of RapidNJ tree: -27432491.036
>--------------------------------------------------------------------
>|             INITIALIZING CANDIDATE TREE SET                      |
>--------------------------------------------------------------------
>Generating 98 parsimony trees...

This is my commandline: `iqtree2 -s AURISMAR2.fas -alrt 1000 -bb 1000 -m Dayhoff --mem 80G -T 16 -st AA`

I would like to know if you are able to tell me if the issue is hardware-related, since there is this warning message. But in any case, could you provide me any guidance to overcome this problem or to speed up the initializing candidate tree set step?

Thank you in advance!

**Comment by roblanf** [comment]
@OliveiraDS-hub how long are your sequences?

**Comment by OliveiraDS-hub** [comment]
@roblanf Thank you for your prompt answer. My sequences are 1,549,093nt

Is it a problem? If so, any advice to overcome it?

**Comment by roblanf** [comment]
My guess here is that parsimony is just very slow with such a long alignment. IQ-TREE is attempting to reconstruct 98 starting trees with parsimony, and that will take a long time.

Better to use another starting tree approach here, like BIONJ using `-t BIONJ`. 

Since this isn't an issue, I'll close this now. Happy to answer more questions in discussions though.
