### ISSUE TITLE
ModelSelection with IQTREE 2 v2.3.4 COVID-edition

### ISSUE THREAD

**Issue by lsjermiin** [iqtree/iqtree2#206]
Hi,

Just picked up new error using the following command:

iqtree2 -s coronaviridae_n2529_catcore_aln_trim20.fasta --seqtype DNA -m MF --mrate E,I,G,*G,I+G,R,*R,I+R,H,*H -cmax 15 --mtree --merit BIC --safe -T 16

The software goes through most substitution models and RHAS models (over the last few months) and then reports:

WARNING: Numerical underflow for lh-derivative-mixlen
WARNING: Numerical underflow for lh-derivative-mixlen
WARNING: Numerical underflow for lh-derivative-mixlen
WARNING: Numerical underflow for lh-ERROR: modelmixture.cpp

The log file 9.88 GB is attached.

All the best,

Lars

**Comment by bqminh** [comment]
I think this one is the same as #208
