### ISSUE TITLE
SIGNAL SEGMENTATION FAULT error (v2.3.4)

### ISSUE THREAD

**Issue by Lfulcrum** [iqtree/iqtree2#207]
Hello,

Thanks for developing IQTree - it's very convenient software!

Recently, I tried running the latest iqtree version (v2.3.4) on a HPC cluster (via a singularity image built from docker image `quay.io/biocontainers/iqtree:2.3.4--h21ec9f0_0`) using the following command:
```
iqtree -s core_gene_alignment.snp.aln -fconst 657934,470789,562235,637172 -B 1000 -m GTR+F -T AUTO --threads-max 8 --prefix VC4130_iq.tree_trial
```

The alignment `core_gene_alignment.snp.aln` contains 4130 sequences.

I noticed a number of recently closed SEGMENTATION FAULT issues that appear to be resolved when using the latest IQTree version, but unfortunately it doesn't seem to work in this case. I attach the log file generated by the run:
[VC4130_iq.tree_trial.log](https://github.com/iqtree/iqtree2/files/15435566/VC4130_iq.tree_trial.log)

We did not exceed the requested resources (see below). We have tried running the same command but with a much smaller subset of the input data (25 sequences) and iqtree runs without error. We also had the same error when running the same command with iqtree v2.2.0.3.

Any help in solving this would be greatly appreciated! Thanks!

**System information**
- `Linux node-10-8-2 5.15.0-101-generic #111-Ubuntu SMP Tue Mar 5 20:16:58 UTC 2024 x86_64`
- 130GB requested
- 8 CPUs requested

**Comment by bqminh** [comment]
It looks like something wrong with the PLL library that we use to infer the initial parsimony tree. Can you add `-t PARS` option and see if that helps? This option is switching to our own parsimony function, which may help.

**Comment by Lfulcrum** [comment]
> It looks like something wrong with the PLL library that we use to infer the initial parsimony tree. Can you add `-t PARS` option and see if that helps? This option is switching to our own parsimony function, which may help.

Thanks for the suggestion @bqminh! We'll give that a try 🙏

**Comment by Lfulcrum** [comment]
Hi @bqminh,

Sorry for the late response! The issue we're facing at the moment is that it is quite a large dataset we are running through the tree and we currently hit a memory limit of 250GB when running with the `-t PARS` option. We are actually hoping to extend the dataset with more sequences and re-run, but it would be helpful to have a way to estimate how much memory would be required?

I notice that iqtree has the `-mem` option, if we set that to 250GB, will the run simply take longer because it has to periodically write to disk?

Many thanks again for you help!

**Comment by bqminh** [comment]
You can do a quick run and IQ-TREE will print the memory required at the beginning. As a rough guideline, the memory requirement is mainly dominated for storing partial likelihood vectors, which can be computed by this equation in bytes:

```
#sequences * #site_patterns * #states * #mixture_classes * #rate_categories * 8
```

where `site_patterns` is the number of distinct site patterns in the alignment, `#states` is 4 for DNA and 20 for protein, `#mixture_classes` is relevant when you use mixture models (e.g. 10 for C10 model), `#rate_categories` is the number of rate categories (e.g. 4 for +G4 model), and the factor 8 is the size of double-precision floating point numbers.

`-mem` option is smarter than what you thought. It doesn't write anything to disk. But IQ-TREE rather will not store all partial likelihoods vectors and need to recompute some vectors when needed: the first factor in the above equation can be smaller than `#sequences`. In my experience if you enforce half of the memory required, the slowdown can be around 10% (which is not much). Note that by default, even without `-mem`, IQ-TREE will automatically detect the available RAM size and adjust -mem if the above equation exceeds your your RAM.
