### ISSUE TITLE
Double 2.3.4 tags

### ISSUE THREAD

**Issue by starsareintherose** [iqtree/iqtree2#218]
Hello, there are two 2.3.4 tags, please help us fix it to avoid confusion

Best regards
Guoyi

**Comment by bqminh** [comment]
Do you mean v2.3.4 and v2.3.4.cmaple? The first one is the official release. Whereas the 2nd one is not (for a paper under review). Please use the v2.3.4 tag.

**Comment by starsareintherose** [comment]
Maybe github issue? But it still shows two tags

![image](https://github.com/iqtree/iqtree2/assets/37733075/3db4926f-fa8f-4236-9fdb-1c08da9bdc09)

**Comment by bqminh** [comment]
I see, I've deleted `v.2.3.4` now. That's a typo when preparing the release. Thanks. @thomaskf please delete that tag from your local repo.

**Comment by trongnhanuit** [comment]
Hi @bqminh,
I've just deleted 'v.2.3.4' from my local repo. So, I am closing this issue now.
