### ISSUE TITLE
Double-quoting numeric values in gCF & sCFL .cf.tree.nex output makes FigTree to sort them as strings

### ISSUE THREAD

**Issue by lccra** [iqtree/iqtree2#225]
gCF .cf.tree.nex example (with or without --df-tree): `...[&gCF="65.96",gCF/gDF1/gDF2/gDFP="65.96/4.26/12.77/17.02",gCF_N="31",gCF_N/gDF1_N/gDF2_N/gDFP_N="31/2/6/8",gDF1="4.26",gDF1_N="2",gDF2="12.77",gDF2_N="6",gDFP="17.02",gDFP_N="8",gN="47"...`

sCFL .cf.tree.nex example: `...[&label="17.3",sCF="43.56",sCF/sDF1/sDF2="43.56/25.7/30.74",sCF_N="43.71",sCF_N/sDF1_N/sDF2_N="43.71/25.78/30.85",sDF1="25.7",sDF1_N="25.78",sDF2="30.74",sDF2_N="30.85",sN="100.3385"]...`

If you were setting something like the colour or thickness of branches by any of these parameters with quoted values, FigTree would sort them hierarchically as strings e.g.

![Untitled](https://github.com/iqtree/iqtree2/assets/171830117/5fd7ee2a-dd63-4f22-b5a0-a8fc34a8166b)

which isn't immediately obvious unless you open up the scale and scroll through the values, or if the colour mapping is clearly abberant for known branch.

Simply removing the quotes fixes this issue.

**Comment by bqminh** [comment]
That's good to know. We can do this in a future release. But for now if you use Mac/Linux, you can run the following command line to remove the quotes of gN values:

```
sed 's/gN="\([0-9.]*\)"/gN=\1/g' XXX.cf.tree.nex > XXX.cf_fixed.tree.nex
```

**Comment by lccra** [comment]
Cheers Bui
