### ISSUE TITLE
Redundant double-bracket ‘((…))’ with closing bracket ending at (line 1 column 6596)

### ISSUE THREAD

**Issue by rubiafilogenetica** [iqtree/iqtree2#227]
Hi, I have read the previous responses but I cannot find the error in my file.
This is the error: edundant double-bracket ‘((…))’ with closing bracket ending at (line 1 column 5220)

[Constraint.txt](https://github.com/user-attachments/files/15775733/Constraint.txt)
Could you please have a look?
Thanks

**Comment by bqminh** [comment]
Well, the error message speaks for itself. This is part of your constraint file ending at that position:

```
((SL131_Phaem)
```

This single taxon `SL131_Phaem` is enclosed in parenthesis, which is not allowed. The parenthesis should include at least 2 taxa, e.g., `(A,B)` or `(A,B,C)`, not just `(A)`.

**Comment by rubiafilogenetica** [comment]
Thanks a lot! I was not able to find the problem!
