### ISSUE TITLE
Integer overflow during memory allocation

### ISSUE THREAD

**Issue by dschrempf** [iqtree/iqtree2#24]
Hi!

Large memory requirements cause a segmentation fault when using mixture models because of integer overflow. This is a long standing bug.

See, e.g.,
- https://github.com/Cibiv/IQ-TREE/issues/171
- https://github.com/dschrempf/EDCluster/issues/1

I have fixed this issue for quite some time on the `linked_models` branch in IQ-TREE 1, see
https://github.com/Cibiv/IQ-TREE/blob/linked_models/model/modelmixture.cpp#L1339 and the following lines.

It would be great if this could be fixed for the distributed versions since I get repeated bug reports for this issue.

Thanks!

**Comment by bqminh** [comment]
Can you make a pull request to iqtree 2? (We're not maintaining iqtree1 anymore). Then I'll review it. I'm closing this issue now.
