### ISSUE TITLE
How to obtain the site frequency for each amino acid site under a homogeneous model

### ISSUE THREAD

**Issue by ZQ1126** [iqtree/iqtree2#246]
Dear Developers,

In C60-PMSF, by using "iqtree2 -st AA -nt 24 -s input.fasta -m LG+C60+F+G -pre C60_sf_input --tree-freq LG_input.treefile", I can obtain a .sitefreq file that contains frequency information at each site.

Now, without specifying a mixture model, I would like to obtain a file similar to .sitefreq (containing frequency information at each site for the amino acid matrix).
When I tried to use "iqtree2 -st AA -nt 24 -s input.fasta -m LG+FO+G -pre LG_FO_sf_input --tree-freq LG_input.treefile" for calculation, I received an error: ERROR: No mixture model was specified!

Is there a way to solve this issue? Alternatively, is there another method to obtain maximum-likelihood optimized base frequencies at each site under a homogeneous model (such as LG+FO+G)?

Best regards,
Qiang

**Comment by roblanf** [comment]
@ZQ1126 this is a misunderstanding of how amino acid models work.

If you specify `LG+FO`, then you are assuming that every site has the same amino acid (not base) frequencies at every site, and that this is optimised via ML. This frequency vector is reported in the IQ-TREE output files.

I suggest reading up about standard amino acid models, profile mixture models, and the PMSF model to get this clear.


Hope that helps,

Rob
