### ISSUE TITLE
problem with start the program in command

### ISSUE THREAD

**Issue by zeynab1995** [iqtree/iqtree2#252]
Hi, after installing the iq-tree I cannot use it in the command prompt, all the time I get this message: The system cannot find the path specified.

could you please help me for this problem?

**Comment by thomaskf** [comment]
Hi,
Are you running IQ-TREE under Linux? It seems that it cannot find the program iqtree2.
If you are working under the folder containing the executable file iqtree2, then you need to type ./iqtree2 [options]
Another way is to run iqtree2 with a full path. That means you can type:  [full path]/iqtree2 [options]
Thomas

**Comment by zeynab1995** [comment]
Dear Thomas,
Thank you for your email.
Actually I download the old version for windows.
But after installing and writing the code, I just got that massage.
Could you please let me know how can I fix it.
Additionally, I should say that I want to use it for the first time.

Best,
Zeynab

**Comment by thomaskf** [comment]
Hi Zeynab,
I see. According to the error message, the system seems unable to find the iqtree2.exe executable file.
The system first searches for the program (i.e. iqtree2.exe) in the folder where you run the command. Then, it searches for the program according to the PATH environment variable.
You can add the folder that contains the iqtree2 into the PATH variable.
You can refer to https://www.wikihow.com/Change-the-PATH-Environment-Variable-on-Windows, which shows how to add a folder to the PATH variable.
Another option is copying iqtree2.exe into the folder where you run the analysis.
Thomas

**Comment by zeynab1995** [comment]
Dear Thomas,
I hope this email finds you well.

I've tried to change the path, but it's not working. Additionally, I copied
the folder where the analysis was located, but the error continues to
appear.

Maybe I did something wrong?

Best,
Zeynab

**Comment by roblanf** [comment]
@zeynab1995, if you're struggling to figure out how to use the command line on windows, you could try the IQ-TREE webserver:

http://iqtree.cibiv.univie.ac.at/

**Comment by zeynab1995** [comment]
Hi,
Actually now I can pass this part but after inserting the file and
reordering again the error appears.

C:\Users\Zeinab\Downloads\iqtree-1.6.12-Windows>bin\iqtree -s
C:\Users\Zeinab\Desktop\sequence.txt -alrt 1000 -bb 1000 -nt AUTO
The system cannot find the path specified.

Do you know the solution?

Best,
Zeynab

**Comment by thomaskf** [comment]
Hi Zeynab,

The command should be: 
bin\iqtree.exe ... 
(instead of bin\iqtree)

I have tried, and the program worked on my side. A screenshot is attached.

![Screenshot 2024-07-02 at 6 12 55 PM](https://github.com/iqtree/iqtree2/assets/18547014/a485848d-ffb4-46c5-b70e-3c0b81c1fd0a)

Thomas

**Comment by zeynab1995** [comment]
so why my pc couldn't run this part
C:\Users\Zeinab\Downloads\iqtree-1.6.12-Windows>bin\iqtree.exe
-s"C:\Users\Zeinab\Desktop\sequence 1.txt" -alrt 1000 -bb 1000 -nt AUTO
The system cannot find the path specified.

I don't know what the problem is. :(


Best
Zeynab

**Comment by thomaskf** [comment]
Hi Zeynab,

Is there an iqtree.exe file in the folder bin?
Can you type the following command in the current directory and show its output?

dir/s


Thomas

**Comment by zeynab1995** [comment]
Hi,
actually, I am using the iqtree app.
sorry but I couldn't understand what you mean.

Best wishes,
Zeynab

**Comment by thomaskf** [comment]
Hi Zeynab,

You typed the command:
C:\Users\Zeinab\Downloads\iqtree-1.6.12-Windows>bin\iqtree -s C:\Users\Zeinab\Desktop\sequence.txt -alrt 1000 -bb 1000 -nt AUTO

And it reported the following error:
The system cannot find the path specified.

How about you type the following command:
C:\Users\Zeinab\Downloads\iqtree-1.6.12-Windows>dir/w

Then, what is the output?
You may show the screenshot.

Based on the output, I may be able to determine the problem.

Again, our IQ-TREE web server, http://iqtree.cibiv.univie.ac.at/, is also available for you to use.

Thomas

**Comment by roblanf** [comment]
Closing this issue, because it's not an issue with IQ-TREE. Feel free to keep asking questions on this thread @zeynab1995, but please don't expect quick answers. We do our best, but it's hard for us to teach people the basics of running things on the command line in a forum like this. Best thing is to see if you can find someone locally who knows how to do it, and ask them to give you a hand.
