### ISSUE TITLE
[BUG] Infinite loop while using BNNI under PMSF model

### ISSUE THREAD

**Issue by StefanFlaumberg** [iqtree/iqtree2#255]
Dear IQ-Tree team,

When running NNI optimization of UFBoot trees under PMSF model, IQ-TREE2 successfully completes the maximum likelihood tree searching steps, but apparently gets stuck afterwards, with the following line being the last thing printed in the log file with no further progress:
`Refining ufboot trees with NNI 1 branch...`

It doesn't go anywhere for considerable time, much exceeding one could expect from the usually quite fast PMSF model behaviour.

The problem is actual for the 2.3.5 version, but according to [this report](https://groups.google.com/g/iqtree/c/nHUSJKvcs2k/m/3GvBZEEeBAAJ) has also been present in previous versions. I hope there is a way to fix it, otherwise it might be worth banning the combination of PMSF and BNNI with printing the relevant warning.

Best regards,
Stefan

**Comment by bqminh** [comment]
Thank you for the report, @diepthihoang can reproduce this bug and will get back to you.

**Comment by StefanFlaumberg** [comment]
Dear @flashhhhh, @bqminh,

Thank you very much! Now everything seems to be working fine.
