### ISSUE TITLE
Error when estimating linked exchangeabilities (GTRpmix)

### ISSUE THREAD

**Issue by mjamy** [iqtree/iqtree2#261]
Dear IQ-TREE team, 

I'm using IQ-TREE v2.3.5 to estimate linked exchangeabilities under the C60 profile mixture model following [this tutorial](http://www.iqtree.org/doc/Estimating-amino-acid-substitution-models#estimating-linked-exchangeabilities). My alignment has 143 taxa and 7,855 sites. 

However, the run crashed almost immediately with the following error:

```
ERROR: modelprotein.cpp:998: virtual void ModelProtein::init(const char*, std::string, StateFreqType, std::string): Assertion `nxs_model' failed.
```

I've attached the log file and input files. 

Thanks!
Mahwash

[iqtree-error.zip](https://github.com/user-attachments/files/16097194/iqtree-error.zip)

**Comment by thomaskf** [comment]
Hi Mahwash,

Thanks for your interest in using the new feature.

It should be "CPREV" instead of "cpREV". That means your command should be:

iqtree2 -s concat_143t_32g_prequal_ginsi_bmge.fasta -m GTR20+C60+G4 --link-exchange -te concat_143t_32g_prequal_ginsi_bmge_cpREV-C60-G.treefile -me 0.99 --init-exchange **CPREV** -nt 20

Thomas

**Comment by thomaskf** [comment]
Thanks for reporting the issue. We will update the codes so that in the next version, the model name with the small letter will be accepted for the option "--init-exchange". For this version, please use the capital letter for the model name as the option "-init-exchange" input.

**Comment by roblanf** [comment]
@thomaskf to clarify further, for the current version should all init models be in all caps? 

E..g if one wanted to use `Q.plant` as an initial model in the current version, should it be adjusted to `Q.PLANT`?

**Comment by thomaskf** [comment]
@roblanf Yes, for the current version, the init model for the option "--init-exchange" needs to be in all caps (e.g. Q.PLANT instead of Q.plant).
