### ISSUE TITLE
using stractural variants (SVs) to build tree by iqtree

### ISSUE THREAD

**Issue by QianghuiZhu** [iqtree/iqtree2#29]
Hi. 
I called stractural variants (SVs) (>50bp) from WGS data. And I want to build a phylogenetic tree by IQtree.

Since SVs data are .vcf files, and IQtree doesn't support this type of file. And I transfer .vcf files into .fasta file according to SVs' genotype. I used "A" to represent "0", "T" to represent "1", and two bases represent one genotype. Then, used this transfered fasta file as input to build tree by IQtree. And got the result as my expect.
commond line: iqtree -s xxx.fasta -nt AUTO -b 1000 -m MFP -pre xxx_MFP

But someone told me that iqtree test the best module based on bases. 
So, I want to know whether it's proper to do as above. Which module is proper for my data? Or what should I do if I want to bulid phylogenetic tree by SVs data.

Thank you.

**Comment by bqminh** [comment]
The proper way is to use IQ-TREE with binary data as it is, not converting to artificial DNA like this. See:

http://www.iqtree.org/doc/Substitution-Models#binary-and-morphological-models
