### ISSUE TITLE
-fast flag

### ISSUE THREAD

**Issue by roblanf** [iqtree/iqtree2#3]
the `-fast` flag should also turn on the following options:

```
--suppress-zero-disatnce
--suppress-list-of-sequences
--suppress-duplicate-sequence
--no-opt-gamma-inv
```

Any others that generally speed things up? 

Perhaps:

```
-optalg 1-BFGS
```

**Comment by JamesBarbetti** [comment]
The -fast flag now turns on the listed options (and also sets the optimisation algorithm to 1-BFGS, as suggested).  I'm not sure how I indicate which commit here.

**Comment by roblanf** [comment]
That's awesome. To point to a commit you can just cut and paste the url to that commit and github makes it look nice.
