### ISSUE TITLE
qustion about the nsite for branch length inference

### ISSUE THREAD

**Issue by longzhangnation** [iqtree/iqtree2#30]
Hi , Thanks for you developing the IQ-TREE2 software. I have a question about the species trees inference . I am using the software r8s , which will use the tree . As mentioned in the forum 'https://www.biostars.org/p/367080/', I donnot not the number of  site for species inference . Here is some of the log when I build the tree ,saying 

-----------
SEQUENCE ALIGNMENT
Input data: 7 sequences with 60206 amino-acid sites
Number of constant sites: 32413 (= 53.8368% of all sites)
Number of invariant (constant or ambiguous constant) sites: 32413 (= 53.8368% of all sites)
Number of parsimony informative sites: 9205
Number of distinct site patterns: 24168
------------
Are these sites used for tree inference ? can you give me a clue about it ? Thank you .

**Comment by bqminh** [comment]
Yes, all sites are included for tree inference. Even the constant sites are "informative" for maximum likelihood, as they help to estimate branch lengths properly.
