### ISSUE TITLE
IQ-TREE CRASHES WITH SIGNAL ABORTED: 'std::ios_base::failure'

### ISSUE THREAD

**Issue by ClarabellaFantilli** [iqtree/iqtree2#304]
Dear developers, 
I have an issue with IQ-TREE 2 (windows) and would appreciate your help. I run the analysis with the following command:
iqtree2.exe -s Version2.fas -m GTR+R7+F -bb 10000 -alrt 1000

I receive the following error:
terminate called after throwing an instance of 'std::ios_base::failure'
  what():  basic_ios::clear
ERROR:
ERROR: *** IQ-TREE CRASHES WITH SIGNAL ABORTED

This is the log file:  [Version2.fas.log](https://github.com/user-attachments/files/16683628/Version2.fas.log)

Thanks in advance

**Comment by thomaskf** [comment]
Dear @ClarabellaFantilli 
Thanks for reporting the issue. Could you send us the alignment file so that we can determine the problem?
You may send the file to my email address: thomaskf@gmail.com
Thanks,
Thomas

**Comment by ClarabellaFantilli** [comment]
Dear @thomaskf 

I have sent the files via email. 
Thanks 
Clarabella

**Comment by ClarabellaFantilli** [comment]
Dear @thomaskf 
Thank you for your assistance. I’ll try to get a Linux machine to run the analysis and will also await your analysis with Windows.

Thanks again.

**Comment by thomaskf** [comment]
Dear @ClarabellaFantilli 
I just tried on a Windows machine; the same command worked on your data set.
Can you check whether you have permission to create a file in the folder where you run the program? IQ-TREE creates the log and result files.
If the problem persists, please consider running IQ-TREE on a Linux or Mac machine.
Thomas

**Comment by ClarabellaFantilli** [comment]
@thomaskf 
I will consider your suggestions. 
Thank you for being so helpful.

Anabella

**Comment by thomaskf** [comment]
Dear @ClarabellaFantilli 
Should you have any questions, please feel free to let us know. I am closing this issue now.
Thomas

**Comment by alexandremissassi** [comment]
Dear @ClarabellaFantilli,

I had the same ERROR Code, pulling up just iqtree2.exe at the prompt. To complete the analysis, it was necessary to provide the path of the entire bin folder.

I hope I've helped. 

Best wishes 

Alex
