### ISSUE TITLE
build failure with -DIQTREE_FLAGS=single

### ISSUE THREAD

**Issue by reneeotten** [iqtree/iqtree2#32]
when trying to compile iqtree2 (both from `master` or the `v1.2.3` tag) without `omp` I get the following failure:

```
tree/phylotree.cpp:3366:25: error: use of undeclared identifier 'omp_get_thread_num'
        int threadNum = omp_get_thread_num();
```

which makes sense as it should likely be in an ```#ifdef _OPENMP``` statement; perhaps like this?

```
#ifdef _OPENMP
    int threads = omp_get_max_threads();
#else 
    threads = 1;
```

**Comment by JamesBarbetti** [comment]
The compilation issue was addressed by commit 9570c601b936cc1a4b2a81ab88fbd85ee020b693, in May 2021.
