### ISSUE TITLE
Memory issue?

### ISSUE THREAD

**Issue by brmagalis** [iqtree/iqtree2#321]
When running lmap, I was able to get to the quartet likelihoods (for which I chose all), but I'm guessing I ran into a memory issue (see below)? [%iqtree_44855174.txt](https://github.com/user-attachments/files/17047091/iqtree_44855174.txt)

Performing likelihood mapping with all quartets...
Computing 42625820447210 quartet likelihoods (one dot represents 100 quartets).

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
ERROR: STACK TRACE FOR DEBUGGING:
ERROR: 1   funcAbort()
ERROR: 2   ()
ERROR: 3   gsignal()
ERROR: 4   abort()
ERROR: 5   __gnu_cxx::__verbose_terminate_handler()
ERROR: 6   ()
ERROR: 7   ()
ERROR: 8   __cxa_rethrow()
ERROR: 9   operator new(unsigned long)
ERROR: 10   std::vector<QuartetInfo, std::allocator<QuartetInfo> >::_M_default_append(unsigned long)
ERROR: 11   PhyloTree::computeQuartetLikelihoods(std::vector<QuartetInfo, std::allocator<QuartetInfo> >&, QuartetGroups&)
ERROR: 12   PhyloTree::doLikelihoodMapping()
ERROR: 13   runTreeReconstruction(Params&, IQTree*&)
ERROR: 14   runPhyloAnalysis(Params&, Checkpoint*, IQTree*&, Alignment*&)
ERROR: 15   runPhyloAnalysis(Params&, Checkpoint*)
ERROR: 16   main()
ERROR: 17   __libc_start_main()
ERROR: 18   ()
ERROR: 
ERROR: *** IQ-TREE CRASHES WITH SIGNAL ABORTED
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: HG02_gp120.fa.log
ERROR: ***    Alignment files (if possible)
/tmp/slurmd/job44855174/slurm_script: line 24: 3351709 Aborted                 (core dumped) iqtree2 -s $file -lmap all

**Comment by thomaskf** [comment]
Yes, it is out of the memory.
From your log file, IQTREE is computing 42625820447210 quartet likelihoods.
It needs around 3K TB memory!
We will add a message to show the memory usage for this step in our future release.
Thank you for reporting the issue.
