### ISSUE TITLE
Output invariant sites position when running +ASC models

### ISSUE THREAD

**Issue by xiekunwhy** [iqtree/iqtree2#328]
Hi,

iqtree auto delete  invariant sites  when running +ASC models, could you please output a file to tell us which site has been deleted?

By the way, how iqtree define "invariant site" ? We filter snps in vcf using maf ( keep which maf >= 0.05 for example), so I think all sites kept after filtering are variant sites, but iqtree still delete a lot of sites but don't tell me which site has been deleted.

Best,
Kun

**Comment by thomaskf** [comment]
Hi Kun,

To check the details for each site, you can use the `-alninfo` option. This will generate a `.alninfo` file, which contains information for every alignment position.

"invariant site" includes three types:
1. Constant sites
2. Constant sites with ambiguous characters
3. Sites with all gaps

Thomas
