### ISSUE TITLE
Error when computing gcf on species tree. 

### ISSUE THREAD

**Issue by hutumpyancha** [iqtree/iqtree2#337]
I am trying to compute the gcf values on my species tree. However it is erroring out everytime for this particular dataset. I am attaching the log file here. I have checked and there are no duplicate trees in the file with the gene trees. The line of code I used was -  iqtree2 -t ASTRAL-MSC-species-tree-50p3.tre --gcf IQtree-gene-50p3.treefile --prefix 50concord
Please let me know if you need any other detail
Upasana
[50concord.log](https://github.com/user-attachments/files/17525605/50concord.log)

**Comment by roblanf** [comment]
This could be because you are using a rooted species tree. Can you try unrooting the input tree first? 

You can do this with `nw_reroot` from newick utils: https://anaconda.org/bioconda/newick_utils

**Comment by hutumpyancha** [comment]
I tried again, it is still not working.

**Comment by roblanf** [comment]
@hutumpyancha, could you attach your input and output files for both runs (with rooted and unrooted target tree) please. I will try to take a look and see what I can figure out.

**Comment by hutumpyancha** [comment]
I redid my species tree on iqtree 2 instead of using the one I had previously made on ASTRAL and the gCF/sCF codes worked now. Thank you so much for looking into it.

**Comment by roblanf** [comment]
Glad it worked! (Though still a bit confused...)

Rob

**Comment by roblanf** [comment]
@mariespe if you can provide your input files and command lines, we can take a look.
