### ISSUE TITLE
Alisim --num-alignments differences between first and subsequent alignments

### ISSUE THREAD

**Issue by elsemikk** [iqtree/iqtree2#338]
Hello,

I have been simulating alignments with alisim (great tool!) and I've noticed some differences between the first and subsequent alignments produced when I make multiple alignments at once using the --num-alignments flag. All of the alignments look reasonable, but the first alignment consistently seems to be an outlier in some metrics such as number of SNPs. For example, when I simulated 100 alignments with --num-alignments 100, the first one had around 380,000 SNPs and the remaining 99 all had around 467,000 to 469,000 SNPs. I thought that was strange so I re-ran the command and it gave the same pattern (the exact numbers of SNPs changed, but the first still had around 380,000 and the subsequent 99 all had 467,000 to 469,000 again). With such a big difference in number of SNPs it seemed as though the first alignment was being produced from a different model than the others - it is 238 standard deviations away from the other 99 in terms of numbers of SNPs. Is this expected?

I then ran the command 100 times while producing one alignment at a time and all 100 iterations gave around 380,000 SNPs, similar numbers to the first alignment in each batch that was made by running --num-alignments 100.

I made iqtree2 phylogenies from the simulated alignments that were run with --num-alignments 100, and the first alignment of the batches of 100 when running with --num-alignments 100 has a few branch lengths that are rather different from the tree I used to simulate the alignments, while the subsequent alignments have branch lengths that are nearly identical to each other and to the tree I used to simulate them.

This is the input tree I used with alisim:
`((((Species1.1:0.0025866798,Species1.2:0.0025866798):0.0017651857,(Species2.1:0.0007699291,Species2.2:0.0007699291):0.0035819364):0.001433348167,(Species3.1:0.0003478916,Species3.2:0.0003478916):0.005437322067):0.01588964401,(Species4.1:0.0036951644,Species4.2:0.0036951644):0.01797969327);
`

The first alignment has some internal branches that are rather different in length from the input tree:
`
((('Species3.1':3.54E-4,'Species3.2':3.48E-4):0.007315,(('Species2.1':7.6E-4,'Species2.2':7.54E-4):0.00365,('Species1.1':0.00259,'Species1.2':0.002572):0.001923):0.005225):0.006711,('Species4.1':0.003796,'Species4.2':0.00383):0.012619);
`

The subsequent alignments have branch lengths very similar to the input tree
`
((('Species3.1':3.52E-4,'Species3.2':3.59E-4):0.005447,(('Species2.1':7.7E-4,'Species2.2':7.64E-4):0.003584,('Species1.1':0.002629,'Species1.2':0.002573):0.001755):0.001433):0.015852,('Species4.1':0.003692,'Species4.2':0.003756):0.017913);
`

This is the command I was using, with iqtree2 v2.3.6:
`iqtree2 --alisim alisim_simulation -m TVM{0.962594/7.2268/0.526296/1.44417}+F{0.239806/0.263377/0.258797/0.23802}+R6{0.287/8.61e-16/0.178/0.629/0.178/0.894/0.173/0.994/0.17/1.04/0.0137/27.7} -t template.treefile --no-copy-gaps --length 10000000 --out-format fasta --num-alignments 100 --prefix alisim_simulation
`

Is there something different about the first alignments in each batch produced by alisim?

**Comment by trongnhanuit** [comment]
Hi @elsemikk,
Thank you for using AliSim and reporting the issue.

We recently fixed a bug (#333), which was caused by the pseudo-random number generators, which might also relate to the issue you're facing. We'll release a new version soon. In the meantime, could you please check if you encounter the same issue using this [pre-release version](https://drive.google.com/drive/folders/11UHemXAhEdyQc17jBglYs8nsAgTV9nil?usp=sharing)? Many thanks!

Nhan

**Comment by elsemikk** [comment]
Thanks! That seems to have fixed it!
With that v2.3.7, now the number of SNPs in the first alignment in the set is within the range of the other 99 in the set (2.1 standard deviations higher than the average instead of 238 standard deviations lower than average) and the phylogeny produced from the first alignment is qualitatively identical to the ones produced by the next alignments and matches the branch lengths of the input tree very well. 

Am I safe to use and cite this pre-release version or should I wait for its official release?

**Comment by trongnhanuit** [comment]
Sounds great!
Thanks, @elsemikk.

As we'll release this version soon (just need some more testings) and the official release will be the same as this one, I think you can start using this version. No need to wait for the official release (to save your time).

Once again, thanks for using AliSim. Please feel free to ping me if you have any question.

Cheers,
Nhan

**Comment by elsemikk** [comment]
Excellent, thank you!
