### ISSUE TITLE
Change sequence name

### ISSUE THREAD

**Issue by kmkocot** [iqtree/iqtree2#36]
Greetings! I am loving the features of iqtree2 but I wanted to point out an issue that caused me a bit of a headache. I understand that some special characters and very long names are problematic, but the automatic changing of sequence name feature kind of messed up a dataset I spent a lot of time curating. It would be helpful if it made a backup of the input file before changing the sequence names.

I"m referring to this sort of thing:
NOTE: Change sequence name 'Acanthomeniidae sp 1 FB-2020 voucher ZSM Mol 20190564|MN531195.1' -> Acanthomeniidae_sp_1_FB-2020
NOTE: Change sequence name 'Acanthomeniidae sp 2 FB-2020 voucher ZSM Mol 20190565|MN531196.1' -> Acanthomeniidae_sp_2_FB-2020
NOTE: Change sequence name 'Acanthomeniidae sp 2 FB-2020 voucher ZSM Mol 20190566|MN531197.1' -> Acanthomeniidae_sp_2_FB-2020
NOTE: Change sequence name 'Acanthomeniidae sp 2 FB-2020 voucher ZSM Mol 20190567|MN531198.1' -> Acanthomeniidae_sp_2_FB-2020
NOTE: Change sequence name 'Acanthomeniidae sp 3 FB-2020 voucher ZSM Mol 20190568|MN531199.1' -> Acanthomeniidae_sp_3_FB-2020
NOTE: Change sequence name 'Acanthomeniidae sp 5 FB-2020 voucher ZSM Mol 20190570|MN531200.1' -> Acanthomeniidae_sp_5_FB-2020
NOTE: Change sequence name 'Acanthomeniidae sp 6 FB-2020 voucher ZSM Mol 20190572|MN531201.1' -> Acanthomeniidae_sp_6_FB-2020
NOTE: Change sequence name 'Acanthomeniidae sp 6 FB-2020 voucher ZSM Mol 20190573|MN531202.1' -> Acanthomeniidae_sp_6_FB-2020
NOTE: Change sequence name 'Acanthomeniidae sp 6 FB-2020 voucher ZSM Mol 20190574|MN531203.1' -> Acanthomeniidae_sp_6_FB-2020
NOTE: Change sequence name 'Acanthomeniidae sp 6 FB-2020 voucher ZSM Mol 20190575|MN531204.1' -> Acanthomeniidae_sp_6_FB-2020
NOTE: Change sequence name 'Acanthomeniidae sp 6 FB-2020 voucher ZSM Mol 20190577|MN531205.1' -> Acanthomeniidae_sp_6_FB-2020
NOTE: Change sequence name 'Acanthomeniidae sp 7 FB-2020 voucher ZSM Mol 20190578|MN531206.1' -> Acanthomeniidae_sp_7_FB-2020
NOTE: Change sequence name 'Acanthomeniidae sp 8 FB-2020 voucher ZSM Mol 20190579|MN531207.1' -> Acanthomeniidae_sp_8_FB-2020

Which led to errors like this later:
ERROR: Duplicated sequence name Acanthomeniidae_sp_2_FB-2020
ERROR: Duplicated sequence name Acanthomeniidae_sp_2_FB-2020
ERROR: Duplicated sequence name Acanthomeniidae_sp_6_FB-2020
ERROR: Duplicated sequence name Acanthomeniidae_sp_6_FB-2020
ERROR: Duplicated sequence name Acanthomeniidae_sp_6_FB-2020
ERROR: Duplicated sequence name Acanthomeniidae_sp_6_FB-2020
ERROR: Duplicated sequence name Acanthomeniidae_sp_SB-1_FB-2020
ERROR: Duplicated sequence name Acanthomeniidae_sp_SB-1_FB-2020

Thanks!
Kevin

**Comment by thomaskf** [comment]
Hi Kevin,
The issue of "ERROR: Duplicated sequence name XXX" has been fixed in version 2.2.0.2 (https://github.com/iqtree/iqtree2/releases/tag/v2.2.0.2).
Thank you!
Thomas
