### ISSUE TITLE
MixtureFinder re-estimates rate heterogeneity across sites models by default

### ISSUE THREAD

**Issue by HS202337** [iqtree/iqtree2#362]
Dear IQ-TREE Developers,

I am running IQ-TREE v2.3.6 (Windows version) on Windows 11 to test how MixtureFinder ([Ren et al., 2024](https://doi.org/10.1101/2024.03.20.586035)) works, using the `example.phy` dataset, located in the IQ-TREE folder. During this analysis, I observed an unexpected behavior: MixtureFinder seems to re-estimate rate heterogeneity across sites (RHAS) models by default (without specifying the `-mrate-twice` option) after selecting the best-fitting mixture of Q-matrices. This behavior is inconsistent with the description in the [Complex models](http://www.iqtree.org/doc/Complex-Models) documentation, which states that MixtureFinder sets `-mrate-twice` to `0` (no)  by default, meaning that it should not re-estimate RHAS models.

Below are the commands used in my analysis and the corresponding log files:

**Default (`-mrate-twice` not specified):**
`iqtree2 -s example.phy -m MIX+MFP -B 1000 -bnni -alrt 1000 -T AUTO --prefix notspecified`
Log file: [notspecified.log](https://github.com/user-attachments/files/17966268/notspecified.log)

**Explicitly setting `-mrate-twice` to `0` (no re-estimation):**
`iqtree2 -s example.phy -m MIX+MFP -mrate-twice 0 -B 1000 -bnni -alrt 1000 -T AUTO --prefix no`
Log file: [no.log](https://github.com/user-attachments/files/17966269/no.log)

**Explicitly setting `-mrate-twice` to `1` (re-estimation enabled):**
`iqtree2 -s example.phy -m MIX+MFP -mrate-twice 1 -B 1000 -bnni -alrt 1000 -T AUTO --prefix yes`
Log file: [yes.log](https://github.com/user-attachments/files/17966270/yes.log)

**Comment by HuaiyanRen** [comment]
The IQTREE version you are using is 2.3.6. MixtureFinder included in this version is not the newest. That's the reason of your question.

To download the newest version of MixtureFinder, you can go to this link: [IQTREE 2.3.5.2.mf](https://figshare.com/articles/dataset/MixtureFinder_logs/24463921?file=49577556)

This is the version we posted in the [MixtureFinder paper manuscript](https://www.biorxiv.org/content/10.1101/2024.03.20.586035v3.full) (in Data and Resource Availability section, there is a Figshare link). 

Once our paper get accepted, we will formally publish the newest MixtureFinder on IQTREE website.

**Comment by HS202337** [comment]
Thank you for your prompt reply.

I tried the same analysis in IQ-TREE v2.3.5.2.mf and MixtureFinder seemed to work properly.

I look forward to the publication of your MixtureFinder paper.
