### ISSUE TITLE
ERROR: alignment sequence X does not appear in the tree

### ISSUE THREAD

**Issue by ctaylor235** [iqtree/iqtree2#370]
When calculating trees for a large set of alignments, error “Alignment sequence X does not appear in the tree” appears sporadically (around 2% of alignments) and inconsistently (most failed alignments succeed if run again with the same settings).

Head of log file for an example that failed:
```
IQ-TREE multicore version 2.1.4-beta COVID-edition for Linux 64-bit built Jun 24 2021
Developed by Bui Quang Minh, James Barbetti, Nguyen Lam Tung,
Olga Chernomor, Heiko Schmidt, Dominik Schrempf, Michael Woodhams.

Host:    comp040.int.ada.nottingham.ac.uk (AVX512, FMA3, 377 GB RAM)
Command: iqtree -s iqtree_testing/OG0009473.fa -T 2
Seed:    161653 (Using SPRNG - Scalable Parallel Random Number Generator)
Time:    Mon Dec  2 16:35:48 2024
Kernel:  AVX+FMA - 2 threads (16 CPU cores detected)
```

Note that this alignment also failed with seeds of 168686 and 831702. But it ran successfully with seed of 694305.

Tail of log file:
```
Computing RapidNJ tree took 1.340949 sec (of wall-clock time) 0.076048 sec (of CPU time)
ERROR: Alignment sequence lcl|NC_067150.1_cds_XP_051012231.1_15522 does not appear in the tree
(lcl|NW_006159842.1_cds_XP_014444760.1_15187,(lcl|CM009249.2_cds_PNI65868.1_50183,lcl|NC_000011.10_cds_NP_006491.2_77660),(((((lcl|NC_037342.1_cds_NP_001103532.1_34392,lcl|NC_080194.1_cds_XP_057551984.1_32545),lcl|NC_046294.1_cds_XP_032977023.1_20800),lcl|NC_080746.1_cds_XP_058401007.1_11060),lcl|NC_006587.3_cds_XP_022273915.1_9218),((lcl|NC_051312.1_cds_XP_037697646.1_20376,lcl|NW_003573478.1_cds_XP_003418238.1_30838),(lcl|NC_041738.1_cds_XP_028931977.1_20752,lcl|NC_050574.1_cds_XP_036600317.1_8825))));
ERROR: Tree taxa and alignment sequence do not match (see above)

```

On searching, I have seen similar issues reported in the past but they appear to have been fixed in more recent versions. 

Many thanks!

**Comment by thomaskf** [comment]
Hi,
Thanks for your message. It seems that the issue should have been addressed in the newer version.
Can you download and use the latest version from https://github.com/iqtree/iqtree2/releases and see whether the issue still exists?

**Comment by ctaylor235** [comment]
Thanks Thomas! Apologies, I hadn't realised I was running such an old version (installed it from conda a few weeks ago). I have updated and am running a test batch to see if it is resolved.

**Comment by ctaylor235** [comment]
Yes, all sorted after the update :)

**Comment by thomaskf** [comment]
> Thanks Thomas! Apologies, I hadn't realised I was running such an old version (installed it from conda a few weeks ago). I have updated and am running a test batch to see if it is resolved.

No worry. I'm glad that the issue disappears in the latest version. Thanks for the message and using IQ-TREE2.
