### ISSUE TITLE
MixtureFinder unexpectedly crashes

### ISSUE THREAD

**Issue by HS6986** [iqtree/iqtree2#371]
Dear IQ-TREE Developers,

I am running [IQ-TREE v2.3.5.2.mf (Windows Version)](https://figshare.com/articles/dataset/MixtureFinder_logs/24463921?file=49577556) on Windows 11 to test how the latest version of MixtureFinder ([Ren et al., 2024](https://doi.org/10.1101/2024.03.20.586035)) works, using [my own empirical dataset](https://github.com/user-attachments/files/18095022/Priapulida.zip). During this analysis, MixtureFinder unexpectedly crashed while selecting the best-fitting 3-class model with the following message.

```
NOTE: Restoring information from model checkpoint file Priapulida.fas.model.gz
NOTE: MixtureFinder 3-class models requires 20 MB RAM!
ModelFinder will test up to 22 DNA models (sample size: 6893 epsilon: 0.100) ...
 No. Model         -LnL         df  AIC          AICc         BIC
ERROR: \Users\minh\Dropbox\iqtree2\model\modelfactory.cpp:1133: virtual bool ModelFactory::initFromNestedModel(map<std::__cxx11::string, vector<std::__cxx11::string> >): Assertion `itr != checkpoint->end()' failed.
ERROR:
ERROR: *** IQ-TREE CRASHES WITH SIGNAL ABORTED
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: Priapulida.fas.log
ERROR: ***    Alignment files (if possible)
```

[This](https://github.com/user-attachments/files/18095038/Priapulida.fas.log) is the complete log file of the analysis.

I think that this issue is likely due to a bug that has not yet been detected. I would appreciate it if you could investigate the issue and address it if necessary.

**Comment by thomaskf** [comment]
Hi,
Thank you for your message. I attempted to download your data to investigate the issue, but unfortunately, I couldn't access it. Once it's fixed, I will check the issue.
Thanks again for your help!

**Comment by HS202337** [comment]
Thank you for your prompt reply. I apologize for the inconvenience.

I have updated the URL. Could you check if you can access it? The dataset should be downloaded as a zip file.

**Comment by thomaskf** [comment]
Thank you! We are working on this.

**Comment by HuaiyanRen** [comment]
Hello,

We've fixed this bug and posted the new version [iqtree-2.3.6.7.mf](https://figshare.com/articles/dataset/MixtureFinder_logs/24463921) to the FigureShare folder mentioned in the MixtureFinder manuscript.

We hope it work well for you.

Thank you again for this information.

**Comment by HS6986** [comment]
Thank you! The new version of MixtureFinder seems to work properly. I am glad I could be of help.
