### ISSUE TITLE
iqtree v 2.1.3 - assertion error in alignment.cpp:77

### ISSUE THREAD

**Issue by linsson** [iqtree/iqtree2#38]
Hi all,

After successfully creating varsites file we ran across the following error while using iqtree2 v 2.1.3 :

ERROR: alignment.cpp:77: std::__cxx11::string &Alignment::getSeqName(int): Assertion `i >= 0 && i < (int)seq_names.size()' failed.
ERROR: STACK TRACE FOR DEBUGGING:
ERROR:
ERROR: *** IQ-TREE CRASHES WITH SIGNAL ABORTED
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: AS.pruning-0.5.log
ERROR: ***    Alignment files (if possible)

I am attaching the log file
[AS.pruning-0.5.log](https://github.com/iqtree/iqtree2/files/7068492/AS.pruning-0.5.log)

Could you please help us in handling this error?

Thanks in advance.

**Comment by corneliusroemer** [comment]
I also got this error and it drove me mad.

I couldn't pin it down. A reboot fixed it. Very strange.

`IQ-TREE multicore version 2.1.4-beta COVID-edition for Mac OS X 64-bit built Jun 24 2021`

```
 ERROR: alignment.cpp:77: std::__1::string &Alignment::getSeqName(int): Assertion `i >= 0 && i < (int)seq_names.size()' failed.
```

**Comment by corneliusroemer** [comment]
Now I got the error using version `2.2.0-beta` on centOS.

When I downloaded the fasta file to my local computer and ran the same command that errored on the cluster, no error was thrown.

When I deleted the log files and the potentially corrupted output tree from previous runs it ran through without error. So I guess as a workaround, one can try to remove intermediary output files from iqtree.

By the way, in the new version, the code line has changed, in case anyone googles this.

``` 
ERROR: alignment.cpp:80: std::__1::string &Alignment::getSeqName(int): Assertion `i >= 0 && i < (int)seq_names.size()' failed.
```

**Comment by corneliusroemer** [comment]
I found this relevant message from the maintainer @bqminh in the Google group:

>This line in the log is relevant (just printed right before the error messages):

> `NOTE: Restoring information from model checkpoint file AS.pruning-0.5.model.gz`

> It means that you had a previous (unfinished) run and IQ-TREE loaded the checkpoint file. From what you wrote below, I’m guessing that you now change the alignment file (-s option). This causes incompability between the checkpoint and the alignment.

> So try to run again with another --prefix and see how it goes.

https://groups.google.com/g/iqtree/c/Gii__XoEIdU/m/w0JsQqEKCwAJ

And indeed, I think I also aborted a previous run and that's when the error appeared.

I'm not quite sure what the easiest workaround is when one hits this error. I also think it would be nice if iqtree would not error in this situation.

**Comment by bqminh** [comment]
Yes, it would have been nice to print such more informative error message... But since you found the answer I'll close this issue.
