### ISSUE TITLE
MixtureFinder crashing 

### ISSUE THREAD

**Issue by isovaline2230** [iqtree/iqtree2#384]
Dear team.

I was running mixturefinder (subst model confined to GTR model) with the following command:

iqtree2 -s ./FcC_supermatrix_NT.fasta -m MIX+MFP -mset GTR -qmax 20 -B 2000 -alrt 1000 -nt AUTO -nm 2000 --runs 10

When testing for a model with 12 q-matrices iqtree crashed with the following error  message:

NOTE: Restoring information from model checkpoint file ./FcC_supermatrix_NT.fasta.model.gz
NOTE: ModelFinder requires 479 MB RAM!
ModelFinder will test up to 1 DNA models (sample size: 11289 epsilon: 0.100) ...
 No. Model         -LnL         df  AIC          AICc         BIC
Restart estimation at the boundary... multiplying all values by random double
Restart estimation at the boundary... multiplying all values by random double
Restart estimation at the boundary... multiplying all values by random double
ERROR: STACK TRACE FOR DEBUGGING:
ERROR: 
ERROR: *** IQ-TREE CRASHES WITH SIGNAL ABORTED
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: ./FcC_supermatrix_NT.fasta.log
ERROR: ***    Alignment files (if possible)

I am appending a log file with the post. Hope I'll be able to know what's wrong. If you also need the alignment file please let me know (FYI it has ~10k sites of 206 species).

Thanks!
[FcC_supermatrix_NT.fasta.log](https://github.com/user-attachments/files/18258739/FcC_supermatrix_NT.fasta.log)

**Comment by thomaskf** [comment]
Hi,

Can you try the latest version of mixtureFinder [iqtree-2.3.6.7.mf](https://figshare.com/articles/dataset/MixtureFinder_logs/24463921) and see whether the problem still exists?

We will incorporate this latest version of mixtureFinder and make a new release of IQ-TREE2 shortly.

Thanks.

**Comment by isovaline2230** [comment]
The new version seems to run smoothly without this error. Thanks!
