### ISSUE TITLE
Issue with IQTREE2  after Performing Nearest Neighbor interchange

### ISSUE THREAD

**Issue by jacobbowman2015** [iqtree/iqtree2#43]
Hello, 

I am using IQTREE multicore 2.0.3 for Linux 64-bit for ancestral reconstructions with this command: 

iqtree -s gene_20.fasta -st NT2AA -t ../Gorilla.tree -m MF --ancestral --threads-max 4 --keep-ident --safe -fast

I keep getting an error after the "Performing Nearest Neighbor interchange..." stage. 

ERROR: phylotree.cpp:3575: virtual NNIMove PhyloTree::getBestNNIForBran(PhyloNode*, PhyloNode*, NNIMove*): Assertion `node1->degree() == 3 && node2->degree() == 3' failed.

[gene_20.fasta.log](https://github.com/iqtree/iqtree2/files/7522754/gene_20.fasta.log)
[Gorilla.tree.txt](https://github.com/iqtree/iqtree2/files/7522758/Gorilla.tree.txt)
[gene_20.fasta.log](https://github.com/iqtree/iqtree2/files/7522760/gene_20.fasta.log)

Is there an issue that I'm doing with my command? Or can I resolve this? 

Thank you so much for the help,
Jacob Bowman

**Comment by bqminh** [comment]
It is because your input tree file `../Gorilla.tree` is a multifurcating tree. NNI only works on bifurcating trees. So please make your tree bifurcating and then you can use input it with `-t` option.
