### ISSUE TITLE
ModelFinder playing up

### ISSUE THREAD

**Issue by lsjermiin** [iqtree/iqtree2#46]
When using the command:

iqtree2 -s data.fst -st AA -m MF -msub nuclear -mtree -T 24 -merit BIC -safe

I expected the code to search tree space for every model of sequence evolution, which combines:

1. all the nuclear substitution models for amino acids (i.e., LG, WAG, JTT, ...)
2. the E,I,G,I+G,R[n] rate-heterogeneity across sites (RHAS) models

However, as the following check shows, the program skipped a large number of RHAS models for some of the substitution models:

grep "===>" data.fst.log 
===> Testing model LG
===> Testing model LG+I
===> Testing model LG+G4
===> Testing model LG+I+G4
===> Testing model LG+R2
===> Testing model LG+R3
===> Testing model LG+R4
===> Testing model LG+R5
===> Testing model LG+R6
===> Testing model LG+F+R5
===> Testing model WAG+R5
===> Testing model WAG+F+R5
===> Testing model JTT+R5
===> Testing model JTT+F+R5
===> Testing model Q.pfam+R5
===> Testing model Q.pfam+F+R5
===> Testing model JTTDCMut+R5
===> Testing model JTTDCMut+F+R5
===> Testing model DCMut+R5
===> Testing model DCMut+F+R5
===> Testing model VT+R5
===> Testing model VT+F+R5
===> Testing model PMB+R5
===> Testing model PMB+F+R5
===> Testing model Blosum62+R5
===> Testing model Blosum62+F+R5
===> Testing model Dayhoff+R5
===> Testing model Dayhoff+F+R5

Things start going wrong after testing the LG+R6. For example, the LG+F, LG+F+I, LG+F+G, LG+F+I+G, LG+F+R2, LG+F+R3 and LG+F+R4 models are all missing.

**Comment by bqminh** [comment]
This is now discussed in https://github.com/iqtree/iqtree2/discussions/193, thus I will close this issue to avoid duplicate.

**Comment by lsjermiin** [comment]
Happy to close #46, as this is subsumed in #193.

Lars

From: Bui Quang Minh ***@***.***>
Date: Friday, 17 May 2024 at 08:43
To: iqtree/iqtree2 ***@***.***>
Cc: Jermiin, Lars ***@***.***>, Author ***@***.***>
Subject: Re: [iqtree/iqtree2] ModelFinder playing up (Issue #46)
EXTERNAL EMAIL: This email originated outside the University of Galway. Do not open attachments or click on links unless you believe the content is safe.
RÍOMHPHOST SEACHTRACH: Níor tháinig an ríomhphost seo ó Ollscoil na Gaillimhe. Ná hoscail ceangaltáin agus ná cliceáil ar naisc mura gcreideann tú go bhfuil an t-ábhar sábháilte.


Closed #46<https://github.com/iqtree/iqtree2/issues/46> as completed.
