### ISSUE TITLE
ModelFinder issue - Numerical Underflow

### ISSUE THREAD

**Issue by lsjermiin** [iqtree/iqtree2#48]
I'm working on a new approach to model selection (lets call it ModelFinder2). It incorporates a different algorithm to traverse models of substitution and models of rate heterogeneity across sites, and it incorporates the new GHOST models. I am using IQ-TREE 2.1.3 for this, but I am encountering various problems, including this error message:

WARNING: Numerical underflow for lh-derivative-mixlen 

Currently, I have log files (+165Mb), which predominantly include this line. I don't think it is necessary to report the warning every time the issue arises (i.e., once should be enough for the model in question).

To handle this issue I sometimes have to stop the program, remove all copies of the warning from the *.log file, and then start the program again. Surely, this should not be necessary.

Can this be arranged?

**Comment by corneliusroemer** [comment]
I also get this error when running on a self-compiled version on my M1 using this homebrew recipe: https://github.com/Homebrew/homebrew-core/blob/573b15f29e31ba4143ae8137111cf87a3f181829/Formula/iqtree2.rb

Interestingly, I don't get any underflow error when running with the official osx-64 binary. Adding `-safe` doesn't help.

**Comment by thomaskf** [comment]
This issue has been resolved in the version 2.3.4 or later. The issue is closed now.
