### ISSUE TITLE
Which releases should be considered stable?

### ISSUE THREAD

**Issue by corneliusroemer** [iqtree/iqtree2#49]
Thanks for making IQtree, we use it extensively for all nextstrain builds and as part of Nextclade. Very useful.

I'm a little confused about your release management. A lot of beta releases, then there's a release but it's marked pre-release. Then there's another one marked latest but it's also beta.

Could you maybe clarify which version you recommend me to use?

![image](https://user-images.githubusercontent.com/25161793/146285366-a2df15ad-3632-4e2c-afa9-2d26cb41a033.png)

![image](https://user-images.githubusercontent.com/25161793/146285393-f15ef354-a439-4787-b29c-f8fd351dd409.png)

**Comment by bernt-matthias** [comment]
Just wanted to ask the same question.

**Comment by corneliusroemer** [comment]
Maybe @thomaskf can help, he did the latest release, 22h ago, of 2.2.1-beta

Does it mean anything that you call it beta?

Why do all of the releases since 2.1.2 contain beta? Because none of them are sufficiently tested?

**Comment by bqminh** [comment]
v2.3.4 ;-)
