### ISSUE TITLE
Include +I+R models

### ISSUE THREAD

**Issue by roblanf** [iqtree/iqtree2#55]
Currently, we don't examine +I+R models by default, but looking at a bunch of empirical datasets suggests that these models are often the best.

To fix this, we just need to change what happens when:

1. `-mrate all` and 
2. `--merge-rate all`
3. the default settings for MF2 when `-mrate` and `--merge-rate` are not set

The only change is that the set of rate distributions considered should now be:

`E,G,I,R,I+G,I+R`

**Comment by roblanf** [comment]
Just to add some evidence. Here's an analysis of a dataset from Endicott and Ho (2008), after merging partitions etc.

4 out of 6 final partitions have +I+R as the best model.

```
TN+F+I+R3: dloop,                                                                                                                  
HKY+F+I+R3: a61_c11_c21_c31_cytb1_n11_n31_n41_n4l1_n51,                                                                            
TPM3u+F+I: a62_c12_c22_c32_cytb2_n12_n22_n32_n42_n4l2_n52_n62,                                                                     
TIM3+F+I+R2: a63_a83_c13_c23_c33_cytb3_n13_n23_n33_n43_n4l3_n53,                                                               
HKY+F+I+R2: a81_a82_n21_12s_loops_16s_loops,                                                                                   
TN+F+G4: n61_n63;                                                                                                              
```

The reason it's a good model is that +R models can't have a rate category of zero, but +I+R (of course) do.

**Comment by roblanf** [comment]
@bqminh tagging you as discussed!

**Comment by thomaskf** [comment]
A new branch called **mf2** has been created.
This request has been addressed in the branch **mf2**.

**Comment by thomaskf** [comment]
To download and compile the source codes in the branch **mf2** :
```
git clone --recursive https://github.com/iqtree/iqtree2
cd iqtree2
git checkout mf2
mkdir build
cd build
cmake -DUSE_LSD2=ON ..
make -j
```
