### ISSUE TITLE
Build for aarch64-linux 

### ISSUE THREAD

**Issue by rwilliams** [iqtree/iqtree2#67]
I'm keenly interested in having a working `aarch64-linux` build for IQ-Tree. It looks like there has been work done to getting it to work on the new M1 Macs ([#42](https://github.com/iqtree/iqtree2/issues/42)) If someone could point me in the right direction to get started I'd be happy to take a stab at this myself.

Cheers,
Ron

**Comment by trongnhanuit** [comment]
Dear Ron,
I have compiled a very initial build of IQ-TREE for M1 Mac by adopting "[IQ-TREE : ARM NEON Implementation](https://github.com/joshlvmh/iqtree_arm_neon)" by Joshlvmh. However, that initial build still needs further improvements.
For the implementation, you can have a look at the following commits:
- [44bfe3d](https://github.com/iqtree/iqtree2/commit/44bfe3d2a456034c6e3203467cf5ef836a729ad6)
- [15195c8](https://github.com/iqtree/iqtree2/commit/15195c8a34d88be09205e56fd03a080ad149804c)
- [748f436](https://github.com/iqtree/iqtree2/commit/748f436ac31e344c139a24939bfcb7461e932041)

The key idea is to detect the ARM architecture by `#if !defined(__ARM_NEON)` and implement the corresponding codes for that architecture.
I think you can try similar things for `aarch64`. Hope it help.
Cheers,
Nhan

**Comment by rwilliams** [comment]
@trongnhanuit Can you assign this to me so I don't forget I want to get to it :)

Cheers,
Ron

**Comment by jianshu93** [comment]
any updates on this？ Can it be successfully compiled？


Thanks

Jianshu

**Comment by rwilliams** [comment]
We're going to start working on it on our end in the next few days. 

Cheers,
Ron

**Comment by davidecarlson** [comment]
Hi all, I was just curious if there is an update on the aarch64 build?
Thanks!
Dave

**Comment by martin-g** [comment]
Hi!
I've created a Pull Request that adds support for Linux ARM64 to CMakeLists.txt - https://github.com/iqtree/iqtree2/pull/148
I also added CI based on Github Actions for Linux x86_64 and aarch64. You could see the results at my fork - https://github.com/martin-g/iqtree2/actions/runs/6768981048
The build for x86_64 is green but I'm still fixing the missing OS dependencies for the aarch64 one!

**Comment by corneliusroemer** [comment]
It would be great if `linux-aarch64` builds could be enabled - bioconda recently added support for that. It would also be useful for arm docker images that can run without qemu on arm macs.
