### ISSUE TITLE
Phylogeny Question

### ISSUE THREAD

**Issue by TommyH-Tran** [iqtree/iqtree2#73]
Does anyone know whether it is better to create a phylogeny using the conservative core genes vs the soft core genes? I know using the conservative core genes is the standard. However, I feel like using the soft core (genes present in 95% of the genomes) might provide higher resolution? Due to the extra genes included. Especially when an outgroup (closely related species to help root the tree) is added.

**Comment by roblanf** [comment]
Hi Tommy,

This is a good question, but it's one for the IQ-TREE forum (https://groups.google.com/g/iqtree) or something more general like Twitter. 

If you post on the IQ-TREE forum, I'd recommend trying to give some more details of what you're trying to do. E.g. what taxa you work on, some information about the genomes, what the aim of your study is (e.g. what the phylogeny is for), information on the numbers of genes, lengths of the alignments, tree depths, etc. The more information, the more useful the responses you get on the forum will be.

Cheers,

Rob
