### ISSUE TITLE
 STACK TRACE FOR DEBUGGING erro

### ISSUE THREAD

**Issue by haiyun-fan** [iqtree/iqtree2#80]
Hi I recently encountered a problem. When running iqtree, I reported the following errors:

1761  cpREV+F+R9    105550.762   1054 213209.523   2437149.523  217653.826
1762  cpREV+F+R10   105544.540   1056 213201.079   2445585.079  217653.815
WARNING: NONREV model will estimate 379 substitution rates that might be overfitting!
WARNING: Please only use NONREV with very large data and always test for model fit!
1794  NONREV+FO+R9  103412.310   1415 209654.619   4216934.619  215621.117
WARNING: NONREV model will estimate 379 substitution rates that might be overfitting!
WARNING: Please only use NONREV with very large data and always test for model fit!
1795  NONREV+FO+R10 103401.691   1417 209637.382   4228249.382  215612.313
WARNING: NONREV model will estimate 379 substitution rates that might be overfitting!
WARNING: Please only use NONREV with very large data and always test for model fit!
1827  NONREV+F+R9   103411.866   1434 209691.731   4325271.731  215738.344
WARNING: NONREV model will estimate 379 substitution rates that might be overfitting!
WARNING: Please only use NONREV with very large data and always test for model fit!
1828  NONREV+F+R10  103401.590   1436 209675.180   4336739.180  215730.226
WARNING: GTR20 model will estimate 189 substitution rates that might be overfitting!
WARNING: Please only use GTR20 with very large data and always test for model fit!
ERROR: checkpoint.h:216: bool Checkpoint::getArray(std::string, int, T*) [with T = double; std::string = std::__cxx11::basic_string<char>]: Assertion `next_pos == string::npos' failed.
ERROR: STACK TRACE FOR DEBUGGING:
ERROR: 1   funcAbort()
ERROR: 2   ()
ERROR: 3   gsignal()
ERROR: 4   abort()
ERROR: 5   ()
ERROR: 6   ()
ERROR: 7   ModelProtein::restoreCheckpoint()
ERROR: 8   ModelFactory::restoreCheckpoint()
ERROR: 9   CandidateModel::evaluate[abi:cxx11](Params&, ModelCheckpoint&, ModelCheckpoint&, ModelsBlock*, int&, int)
ERROR: 10   CandidateModelSet::test(Params&, PhyloTree*, ModelCheckpoint&, ModelsBlock*, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)
ERROR: 11   runModelFinder(Params&, IQTree&, ModelCheckpoint&)
ERROR: 12   runPhyloAnalysis(Params&, Checkpoint*, IQTree*&, Alignment*&)
ERROR: 13   runPhyloAnalysis(Params&, Checkpoint*)
ERROR: 14   main()
ERROR: 15   __libc_start_main()
ERROR: 16   ()
ERROR: 
ERROR: *** IQ-TREE CRASHES WITH SIGNAL ABORTED
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: /home/fhy/program/PlantGenome/SHU_orthofinder/02-lowcopy_seq/LCN_OGs_filter/family2/OG0007022.fa.log
ERROR: ***    Alignment files (if possible)

I don't know what the problem is. I'm looking forward to your comments!

**Comment by trongnhanuit** [comment]
Hi haiyun-fan,
I think this issue may relate to another bug that has already been fixed. Can you please replicate your test on the version [2.2.0](https://github.com/iqtree/iqtree2/releases/tag/v2.2.0) or [2.2.0.2](https://github.com/iqtree/iqtree2/releases/tag/v2.2.0.2)? Please let me know whether this issue still occurs on these versions? If yes, please share with me your input data and the testing command that you used. Many thanks!

Cheers,
Nhan

**Comment by haiyun-fan** [comment]
[OG0008012.zip](https://github.com/iqtree/iqtree2/files/8583444/OG0008012.zip)

**Comment by haiyun-fan** [comment]
> Hi haiyun-fan, I think this issue may relate to another bug that has already been fixed. Can you please replicate your test on the version [2.2.0](https://github.com/iqtree/iqtree2/releases/tag/v2.2.0) or [2.2.0.2](https://github.com/iqtree/iqtree2/releases/tag/v2.2.0.2)? Please let me know whether this issue still occurs on these versions? If yes, please share with me your input data and the testing command that you used. Many thanks!
> 
> Cheers, 



I have uploaded files and commands, and look forward to your comments!@Nhan

**Comment by trongnhanuit** [comment]
Hi haiyun-fan,
Did you download version 2.2.0 after March 25, 2022? We fixed minor bugs and updated the release on that day.
I'm testing your data with that version and have not yet found that issue. My test is still running but I think it passed over the point where you had the issue. Can you double-check it with the latest version?
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/7534124/165886518-b8de04f3-f1d3-4c35-a0bb-6f5cae42bb5e.png">

Cheers,
Nhan

**Comment by haiyun-fan** [comment]
Thank you for your reply. I'm trying the latest version.

**Comment by trongnhanuit** [comment]
According to my tests on the newer versions, I didn't encounter that issue. Therefore, I close it now.
