### ISSUE TITLE
Rootstrap error obtained for tutorial example

### ISSUE THREAD

**Issue by magibc** [iqtree/iqtree2#81]
Dear IQTREE developers,

I desire to root my phylogenetic trees obtained from a shotgun metagenomics study.

I've updated IQTREE1.6.12 to IQTREE 2.2.0.3 in order to be able to use the rootstrap tool: http://www.iqtree.org/doc/Rootstrap

I work in Ubuntu.

I've tried to perform the first example of tutorial in the abovementioned webpage:

Command:
iqtree2 -s bovidae_outgroup.phy -p bovidae.nex -B 1000 -T AUTO --prefix rev_dna_outg

Output:
Create initial parsimony tree by phylogenetic likelihood library (PLL)... 0.003 seconds
Measuring multi-threading efficiency up to 48 CPU cores
Increase to 10 rounds for branch lengths
ERROR: STACK TRACE FOR DEBUGGING:
ERROR: 1   funcAbort()
ERROR: 2   ()
ERROR: 3   MTree::printBranchLength(std::ostream&, int, bool, Neighbor*)
ERROR: 4   MTree::printTree(std::ostream&, int, Node*, Node*)
ERROR: 5   MTree::printTree(std::ostream&, int, Node*, Node*)
ERROR: 6   MTree::printTree(std::ostream&, int)
ERROR: 7   PhyloTree::generateRandomTree(TreeGenType)
ERROR: 8   PhyloTree::testNumThreads()
ERROR: 9   PhyloTree::ensureNumberOfThreadsIsSet(Params*)
ERROR: 10   computeFastMLTree(Params&, Alignment*, ModelCheckpoint&, ModelsBlock*, int&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
ERROR: 11   runModelFinder(Params&, IQTree&, ModelCheckpoint&)
ERROR: 12   runPhyloAnalysis(Params&, Checkpoint*, IQTree*&, Alignment*&)
ERROR: 13   runPhyloAnalysis(Params&, Checkpoint*)
ERROR: 14   main()
ERROR: 15   __libc_start_main()
ERROR:
ERROR: *** IQ-TREE CRASHES WITH SIGNAL SEGMENTATION FAULT
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: rev_dna_outg.log
ERROR: ***    Alignment files (if possible)

After I have tried with my data (in my case I do not have a partition file but I think it's not a problem) and I obtained the same error.

For this I post here if someone has been encountered with the same problem and could help me.

Many thanks on advance for your help,

Magí

**Comment by thomaskf** [comment]
Hi Magi,

Thanks for your message. Can you please download version 2.2.0.3 again? The problem was identified and we have updated the version in a few hours. Thanks.

**Comment by magibc** [comment]
hi @thomaskf ,
Now works like a charm!

Thank you,
David.
