### ISSUE TITLE
M1 arm64 iqtree2 crashes if "ASSERT(newPInvar < 1.0)" in rategammainvar.cpp is false

### ISSUE THREAD

**Issue by HRG1** [iqtree/iqtree2#82]
This occurs in sequential and open-mpi builds, independent of nucleic/protein input.

There are old reports to that effect from 2018 and 2019:

https://groups.google.com/g/iqtree/c/-ngFmcumLA8
https://groups.google.com/g/iqtree/c/ZHGb-q-H9Ck

Is the crash the intended result and depends on the aligned sequences or is this a problem in the code that should be addressed?

IQ-TREE multicore version 2.2.0.3 COVID-edition for Mac OS X 64-bit built May  4 2022
Developed by Bui Quang Minh, James Barbetti, Nguyen Lam Tung,
Olga Chernomor, Heiko Schmidt, Dominik Schrempf, Michael Woodhams, Ly Trong Nhan.

Host:    macstudio.local (SSE4.2, 32 GB RAM)
Command: iqtree2 -m GTR+I+G -s temp -safe
Seed:    227968 (Using SPRNG - Scalable Parallel Random Number Generator)
Time:    Wed May  4 14:05:03 2022
OMP: Info #271: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Kernel:  Safe SSE2 - 1 threads (10 CPU cores detected)

HINT: Use -nt option to specify number of threads because your CPU has 10 cores!
HINT: -nt AUTO will automatically determine the best number of threads to use.

Reading alignment file temp ... Fasta format detected
Reading fasta file: done in 3.8147e-05 secs using 81.26% CPU
Alignment most likely contains DNA/RNA sequences
Constructing alignment: done in 6.00815e-05 secs using 66.58% CPU
Alignment has 8 sequences with 69 columns, 27 distinct patterns
13 parsimony-informative, 12 singleton sites, 43 constant sites
           Gap/Ambiguity  Composition  p-value
Analyzing sequences: done in 1.00136e-05 secs using 59.92% CPU
   1  NC_027833    0.00%    passed     94.21%
   2  NC_030529    0.00%    passed     99.59%
   3  NC_028001    0.00%    passed     87.09%
   4  A            0.00%    passed     99.14%
   5  B            0.00%    passed     80.31%
   6  C            0.00%    passed     90.96%
   7  D            0.00%    passed     98.64%
   8  I            0.00%    passed     82.15%
****  TOTAL        0.00%  0 sequences failed composition chi2 test (p-value<5%; df=3)
Checking for duplicate sequences: done in 1.50204e-05 secs using 66.58% CPU

Create initial parsimony tree by phylogenetic likelihood library (PLL)... 0.000 seconds

NOTE: 0 MB RAM (0 GB) is required!
Estimate model parameters (epsilon = 0.100)
Thoroughly optimizing +I+G parameters from 10 start values...
Rate parameters:  A-C: 1.00000  A-G: 1.00000  A-T: 1.00000  C-G: 1.00000  C-T: 1.00000  G-T: 1.00000
Base frequencies:  A: 0.248  C: 0.130  G: 0.297  T: 0.324
Proportion of invariable sites: 0.000
Gamma shape alpha: 1.000
WARNING: Numerical underflow for lh-derivative
.
.
.
Rate parameters:  A-C: 1.00000  A-G: 1.00000  A-T: 1.00000  C-G: 1.00000  C-T: 1.00000  G-T: 1.00000
Base frequencies:  A: 0.248  C: 0.130  G: 0.297  T: 0.324
Proportion of invariable sites: 0.000
Gamma shape alpha: 1.000
WARNING: Numerical underflow for lh-derivative
ERROR: rategammainvar.cpp:247: double RateGammaInvar::optimizeWithEM(double): Assertion `newPInvar < 1.0' failed.
ERROR: STACK TRACE FOR DEBUGGING:
ERROR: 2   _sigtramp()
ERROR: 5   RateGammaInvar::optimizeWithEM(double) (.cold.3)
ERROR: 6   RateGammaInvar::optimizeWithEM(double)
ERROR: 7   RateGammaInvar::optimizeParameters(double)
ERROR: 8   ModelFactory::optimizeParameters(int, bool, double, double)
ERROR: 9   ModelFactory::optimizeGammaInvWithInitValue(int, double, double, double, double, std::__1::vector<double, std::__1::allocator<double> >&, Checkpoint*)
ERROR: 10   ModelFactory::optimizeParametersGammaInvar(int, bool, double, double)
ERROR: 11   IQTree::optimizeModelParameters(bool, double)
ERROR: 12   IQTree::ensureModelParametersAreSet(double)
ERROR: 13   runTreeReconstruction(Params&, IQTree*&)
ERROR: 14   runPhyloAnalysis(Params&, Checkpoint*, IQTree*&, Alignment*&)
ERROR: 15   runPhyloAnalysis(Params&, Checkpoint*)
ERROR:
ERROR: *** IQ-TREE CRASHES WITH SIGNAL ABORTED
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: temp.log
ERROR: ***    Alignment files (if possible)
zsh: abort      iqtree2 -m GTR+I+G -s temp -safe

used sequence file (-s temp):
```
>NC_027833
AACGAGTATTTTAAAGTGAAGGATTGTGTGCTCTGCAAGCATGAGGTGAGCGTTTTGGCT
CTGTCGTTG
>NC_030529
AACGATGTATTTTAAAATGGAGATTGCGTGCTCTGCAAGTACGAGGTGAGTATTGGAACT
CTGTCGTTG
>NC_028001
AACGATATATTTTAAGATAAAGATTGCATGCTCTGCAAGTATGAGGTGAGTGTGAAGGCT
CTGTCGTTG
>A
AACGATGTATTTTAAGATGAAGATTGCGTGCTCTGCAAGTACGAGGTGAGTGTTGAGTCT
CTGTCGTTG
>B
GACGGTGTATTTTAAGATAGAGATTGCGTGCTCTGCAAGTACGAGGTGAGTGTTTGAGCT
CTGCCGTTG
>C
AACGGTGTATTTTAATGTAAAGATTGCGTGCTCTGCAAGCACGAGGTGAGTATTAGAGCT
CTGCCGTTG
>D
AACGATGTATTTTAAGATGAAGATTGCGTGCTCTGCAAGTATGAGGTGAGTGTTAGGACT
CTGTCGTTG
>I
AACGATATATTTTAAAATGAAGATTGCGTGCTCTGCAAGTATGAGGTGAGTATTGAGACT
CTGTCGTTG
```

**Comment by thomaskf** [comment]
Hi,
Can I ask a few questions to understand the situation?
1. Did you download the source codes and compile them? If so, what commands did you type to compile them?
2. Did you run the program under the M1 MacBook?
Thanks!

**Comment by HRG1** [comment]
Yes, I followed the instructions provided in iqtree2-2.2.0.3/CMakeLists.txt to compile iqtree on a Mac Studio Max.

cmake, boost and open-mpi are required (installed by homebrew) and XCode for clang and the macOS SDK.

IMPORTANT: Update CMakeLists.txt to your current macOS SDK (lines 169/170), in my case macos12.3 and in line 132 change ON to OFF to disable USE_LSD2 (following the CMakeLists.txt file that came with the first iqtree M1 beta,  iqtree2-2.2-beta.tar.gz).

Create a directory (for example ~/Desktop/cmake_iqtree) and cd into it in your terminal application before running cmake:
```
cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ /path/to/iqtree2-2.2.0.3
```
The program runs ok if rategammainvar.cpp is not called.

For example this works: iqtree2 -m GTR -s temp -safe

Good luck

**Comment by bqminh** [comment]
I believe Mac ARM processor (M1 M2 etc) was not supported back then. That could be the reason. But we now support Mac ARM from v2.3.X. So I would assume that this issue is resolved now. But feel free to test it again and if you see that the problem persists, pls reopen it.
