### ISSUE TITLE
IQ-TREE release vs pre-release?

### ISSUE THREAD

**Issue by peterk87** [iqtree/iqtree2#87]
Hello,

I was wondering if a new release rather than pre-release is incoming for IQ-TREE. How should one treat a pre-release vs a release for IQ-TREE? Are pre-releases only for alpha/beta releases, while releases should be treated as production ready? Also, for the IQ-TREE Bioconda package, it seems that only GitHub releases are automatically picked up by the BiocondaBot while pre-releases are ignored  (see https://github.com/bioconda/bioconda-recipes/pulls?q=is%3Apr+iqtree).

Thanks!

**Comment by roblanf** [comment]
You're spot on. A pre-release is something that is not yet production ready. Typically it contains features we're building and/or integrating, that we or our students & collaborators are working on. Anyone is welcome to try a pre-release, but we don't yet vouch for the features in there, and typically we don't have the time (nor would it be wise) to offer lots of help in how to use the new and untested/unfinished features.

Releases are things we vouch for, will do our best to fix bugs in, etc. 

That's what underlies the reason for ignoring pre-releases on bioconda. When people install IQ-TREE on bioconda, we want them to get the most up to date stable version.

**Comment by peterk87** [comment]
Thanks @roblanf for the clarification! That makes a lot of sense. 

I noticed "-beta" was appended to some pre-releases like [v2.1.4-beta](https://github.com/iqtree/iqtree2/releases/tag/v2.1.4-beta). Would it be possible to append "beta" or some other indication of non-stable release to future pre-release tags? Thanks!
