### ISSUE TITLE
ERROR: Tree taxa and alignment sequence do not match reappears in v2.2.0

### ISSUE THREAD

**Issue by edgardomortiz** [iqtree/iqtree2#94]
I downloaded the most recent v2.2.0 (according to the releases https://github.com/iqtree/iqtree2/releases/tag/v2.2.0) and the following error occurred:
```
ERROR: Alignment sequence XXX does not appear in the tree
ERROR: Tree taxa and alignment sequence do not match (see above)
```
However looking at the release notes the issue had been resolved since the previous v2.2.0.3, so I downloaded v2.2.0.4 and the bug was fixed and the analysis finishes correctly

Are the releases in reverse chronological order? am I correct to use 2.2.0.4  in this case?

Thanks

Edgardo

**Comment by thomaskf** [comment]
Dear Edgardo,
Thanks for using IQ-Tree. Yes, the issue was resolved in version 2.2.0.4
too and so it is fine to use 2.2.0.4.
Thanks,
Thomas

**Comment by edgardomortiz** [comment]
Dear Thomas,

Thanks for confirming, I was just confused because v2.2.0 was uploaded 12 days ago and has the bug and v2.2.0.4 was uploaded 18 days ago and has the issue fixed

**Comment by trongnhanuit** [comment]
Dear Edgardo,
That was my mistake, v2.2.0 didn't include recent bugs fixed. 
I've just incorporated all bugs fixed. You now can try the latest release [v2.2.0.5](https://github.com/iqtree/iqtree2/releases/tag/v2.2.0.5). 
Thank you for reporting this issue.

Cheers,
Nhan

**Comment by edgardomortiz** [comment]
Excellent, thanks for confirming

**Comment by bernt-matthias** [comment]
Could someone explain what the bugfix actually is? Should be one of the changes seen here https://github.com/iqtree/iqtree2/compare/v2.2.0.4...v2.2.0.5

Background. The Galaxy tool for iqtree  fails weeky CI with this error (currently version 2.1.2 is wrapped). And I'm wondering why this is the case. At some point in history it did not fail the tests .. so its strange that they are now.
