### ISSUE TITLE
sCF lowercase ambiguous sequence error

### ISSUE THREAD

**Issue by stiatragul** [iqtree/iqtree2#95]
Hey IQTREE2 developers, 

First of all thank you for making such a great program! I have a non-urgent issue to report. I was running concordance factor analyses for gCF and sCF and noticed that for sCF, if my alignment is lowercase, I will get an error for ambiguous characters. 

Here is an example,  aln-all.nex is in lowercase and (v) was not a valid symbol. 

## First run 
```
IQ-TREE multicore version 2.2.0 COVID-edition for Windows 64-bit built Jun  1 2022
Developed by Bui Quang Minh, James Barbetti, Nguyen Lam Tung,
Olga Chernomor, Heiko Schmidt, Dominik Schrempf, Michael Woodhams, Ly Trong Nhan.

Host:    *****-****  (AVX2, FMA3, 31 GB RAM)
Command: C:\tools\iqtree-2.2.0-Windows\bin\iqtree2.exe -t .\20220617_rooted_all_loci.tre --gcf .\20220617_all_loci.trees -s .\aln-all\aln-all.nex --scf 100 --prefix concord
Seed:    652090 (Using SPRNG - Scalable Parallel Random Number Generator)
Time:    Fri Jun 24 10:17:24 2022
Kernel:  AVX+FMA - 1 threads (8 CPU cores detected)

HINT: Use -nt option to specify number of threads because your CPU has 8 cores!
HINT: -nt AUTO will automatically determine the best number of threads to use.

Reading alignment file .\aln-all\aln-all.nex ... Nexus format detected
ERROR:
ERROR: Error found at line 131, column 273 (file position 366606870):
ERROR: State specified (v) for taxon 126, character 222, not found in list of valid symbols
```

## Second run after editing aln-all.nex to aln-all_edit.nex (I just capitalised the 'V' manually.
```
IQ-TREE multicore version 2.2.0 COVID-edition for Windows 64-bit built Jun  1 2022
Developed by Bui Quang Minh, James Barbetti, Nguyen Lam Tung,
Olga Chernomor, Heiko Schmidt, Dominik Schrempf, Michael Woodhams, Ly Trong Nhan.

Host:    *****-**** (AVX2, FMA3, 31 GB RAM)
Command: C:\tools\iqtree-2.2.0-Windows\bin\iqtree2.exe -t .\20220617_rooted_all_loci.tre --gcf .\20220617_all_loci.trees -s .\aln-all\aln-all_edit.nex --scf 100 --prefix concord
Seed:    132416 (Using SPRNG - Scalable Parallel Random Number Generator)
Time:    Fri Jun 24 11:17:50 2022
Kernel:  AVX+FMA - 1 threads (8 CPU cores detected)

HINT: Use -nt option to specify number of threads because your CPU has 8 cores!
HINT: -nt AUTO will automatically determine the best number of threads to use.

Reading alignment file .\aln-all\aln-all.nex ... Nexus format detected
ERROR:
ERROR: Error found at line 131, column 431 (file position 366607028):
ERROR: State specified (r) for taxon 126, character 380, not found in list of valid symbols
```
Now the error is on the next ambiguous character (r). 

To overcome this error I capitalised my sequence. However, just thought I'd let you all know that otherwise the function runs without any other problems for me. Maybe include in the documentation that the ambiguous sequence needs to be capitalised or allow lowercase ambiguous characters.

Thanks again!

Cheers,
Putter

**Comment by bqminh** [comment]
Hi Putter, it's actually a feature when you have a NEXUS input alignment. The nexus format can allow users to ask IQ-TREE whether it should respect the case or not by the keyword "RESPECTCASE" in the FORMAT command of the data/characters block. What I'm suspecting here (as I don't have your nexus file) is that you actually have this keyword in your nexus file. Whereas the default behaviour is to ignore cases.

For other FORMAT (like PHYLIP or FASTA) we treat data as case-insensitive.
