### ISSUE TITLE
Multiple meanings of '-t' option and undescribed node labels

### ISSUE THREAD

**Issue by Gullumluvl** [iqtree/iqtree2#99]
Hi,

I am using IQ-TREE multicore version 2.1.2 COVID-edition for Linux 64-bit built Apr 26 2021.

## Problem

When given a tree with `-t`, iqtree2 recycles the original internal node labels into the output tree, even if topologies differ.

The output tree thus displays _multiple node labels_, separated by slashed, without describing the meaning of all of them.

This seems to stem from `-t` having _multiple meanings_:

    GENERAL OPTIONS:
      -t FILE|PARS|RAND    Starting tree (default: 99 parsimony and BIONJ)

    CONCORDANCE FACTOR ANALYSIS:
      -t FILE              Reference tree to assign concordance factor

    CONSENSUS RECONSTRUCTION:
      -t FILE              Set of input trees for consensus reconstruction

and the user cannot know which meaning is taken.

## Steps to replicate

1. a starting tree must be given with `-t` 
2. the starting tree must have internal labels; when the label is not numeric, we can also see it at the first position.

## Exact command I used

I ran the following command with the intent of providing a starting tree (from a previous iqtree run):

    iqtree2 -T 1 -t previousrun.fast.treefile -m LG+C10+G --alrt 1000 --seqtype AA -s myseq.fa --prefix LGC10alrt

Unexpectedly, I observed that internal node labels have two numeric values, as shown in the .iqtree output:

``` 
NOTE: Tree is UNROOTED although outgroup taxon 'Hsap_NP_001307951.1__1' is drawn at root
Numbers in parentheses are SH-aLRT support (%)

+--Hsap_NP_001307951.1__1
|
| +--Atha_NP_565836.1__1
+--| (77/26.8)
| | +--Acas_XP_004335122.1__1
| +--| (66.6/69.9)
```

The note does not explain why there are 2 values, nor which one is the new support value.

It could even be that I actually ran a concordance factor analysis, but that was not intended. Could you please tell me which meaning is taken, and how to unambiguously provide a starting tree?
Would it be possible to update the NOTE message?

Thanks in advance,

**Comment by bqminh** [comment]
You're right, if the starting tree already has some labels for some branches, which are also present in the final tree, these labels will be reused. New values will be appended to existing labels and IQ-TREE automatically put a slash between them.
In your example, your starting tree has existing labels "77" and "66.6". Then you ask IQ-TREE to compute SH-aLRT supports, which are "26.8" and "69.9", and appended to the branch labels after a slash.

I actually think that this is quite a neat feature. It helps users to directly compare different values (e.g. by different support measures) for every branch of the tree.

If you want to avoid this, just remove the labels (pretty sure that there are R/Python script to do this) before supplying this tree to IQ-TREE via `-t` option.
